-- -----------------------------------------------------------------------------
--  LuiExtended                                                               --
--  Distributed under The MIT License (MIT) (see LICENSE file)                --
-- -----------------------------------------------------------------------------
-- Additional trial/dungeon ability alerts (merged at load). Review in-game.

--- @class (partial) LuiData
local LuiData = LuiData

local Data = LuiData.Data
local AlertTable = Data.AlertTable

local ACTION_RESULT_BEGIN = ACTION_RESULT_BEGIN
local ACTION_RESULT_EFFECT_GAINED = ACTION_RESULT_EFFECT_GAINED
local ACTION_RESULT_EFFECT_GAINED_DURATION = ACTION_RESULT_EFFECT_GAINED_DURATION

local LUIE_ALERT_SOUND_TYPE_ST = LUIE_ALERT_SOUND_TYPE_ST
local LUIE_ALERT_SOUND_TYPE_ST_CC = LUIE_ALERT_SOUND_TYPE_ST_CC
local LUIE_ALERT_SOUND_TYPE_AOE = LUIE_ALERT_SOUND_TYPE_AOE

--- @class (partial) TrialSupplementAlerts
local trialSupplementAlerts =
{

    [103531] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 6600, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [103555] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 400, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [103946] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, minHitValue = 2500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [104019] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 31003, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [105239] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 10000, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [105291] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 600, minHitValue = 1250, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [110431] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 6600, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [111283] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 2000, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [116636] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [117251] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [117324] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [118884] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [120359] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 3100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [120783] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED_DURATION, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [120890] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 2500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [121075] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [121411] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 600, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [121422] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [121436] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [121722] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 6300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [122012] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 2500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [133515] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 4500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [133559] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 200, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [134023] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [134050] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 30400, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [134196] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [136873] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [140606] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [140941] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 400, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [140944] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 400, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [149089] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [150008] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 30000, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [152688] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 2500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [157466] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 30800, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [157860] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 1000, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [163153] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 600, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [163654] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [163952] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 800, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [163987] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [164480] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [166353] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 400, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [166522] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [166525] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [166527] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 400, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [166529] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 400, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [168314] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 1505, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [168525] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [168526] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 400, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [171742] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [172410] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 3300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [182334] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 5300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [182393] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 14500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [183778] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 1103, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [183855] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 45000, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [184802] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 30500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [191702] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [192013] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, maxHitValue = 5000, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [192024] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, minHitValue = 2401, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [192517] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 1500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [193530] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [193534] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [194984] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [195448] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 1100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [195816] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [196235] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [196251] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, hitValueEquals = 3000, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [196689] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 200, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [196715] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [196848] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [196875] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [196959] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [197002] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [198099] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [199344] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [199608] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [201727] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [202374] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, minHitValue = 1501, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [202383] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [203006] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [203492] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [207005] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 1400, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [209645] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [209963] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [209981] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [210830] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [210841] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [211594] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [214136] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [214138] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 20100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [214187] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [214203] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [214355] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 400, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [215107] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 8800, hitValueEquals = 1200, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [218285] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 800, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [219420] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [220298] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [221216] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [221745] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [221792] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 3000, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [222071] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 400, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [222609] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 800, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [223331] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 800, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [223378] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [223685] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [223935] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [224463] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 1102, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [224473] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 1402, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [224476] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 1402, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [224822] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [226181] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 200, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [227461] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, hitValueEquals = 1233, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [229247] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 800, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [230349] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 1102, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [230383] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 1402, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [230386] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 1402, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [232397] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [232773] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [232779] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 400, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [232780] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 400, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [233452] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [233466] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [233477] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [233489] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [233598] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [233610] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [233821] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [234000] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 1405, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [234276] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 1105, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [234704] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [234722] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [235201] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [236381] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 30500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [236569] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [236751] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 1505, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [237149] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [238800] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 800, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [240363] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [240426] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 800, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [240665] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 400, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [241224] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [241326] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [241327] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [241328] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [241329] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [241662] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [241685] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 20200, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [241689] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 30200, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [241854] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [241863] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [242063] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 100, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [246168] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 4300, hitValueEquals = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [250487] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [250667] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [250668] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 200, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [251465] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [252712] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [252715] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 300, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [254918] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [256383] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [256483] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [256579] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 500, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [47898] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [48240] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [49098] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [49506] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [49583] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [56782] = { priority = 1, result = ACTION_RESULT_EFFECT_GAINED, block = true, dodge = true, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [63029] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 900, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [63044] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 900, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },
    [63046] = { priority = 1, result = ACTION_RESULT_BEGIN, block = true, dodge = true, duration = 900, sound = LUIE_ALERT_SOUND_TYPE_ST_CC },

}

for abilityId, entry in pairs(trialSupplementAlerts) do
    AlertTable[abilityId] = entry
end


