---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by david.
--- DateTime: 08/02/2025 15:35
---

local Nav = Navigator
local Node = Nav.Node

--- @class PlayerNode
local PlayerNode = Node:New()

function PlayerNode:GetWeight()
    local w
    if self.isGroupmate then
        w = self.isLeader and 1.3 or 1.2
    elseif self.isFriend then
        w = 1.1
    else
        w = 1.0
    end
    if not self.isOnline then w = w - 0.4 end
    return w
end

function PlayerNode:GetIcon()
    if self.isGroupmate then
        return self.isLeader and "/esoui/art/icons/mapkey/mapkey_groupleader.dds" or "/esoui/art/icons/mapkey/mapkey_groupmember.dds"
    else
        return "Navigator/media/icons/player.dds"
    end
end

function PlayerNode:GetSuffix() return self.isOnline and self.zoneName or "" end

function PlayerNode:GetOverlayIcon()
    if self.isFriend then
        return "Navigator/media/overlays/star.dds", Nav.COLOUR_FRIEND
    else
        return nil, nil
    end
end

function PlayerNode:GetColour(isSelected)
    if isSelected and self.isOnline then
        return Nav.COLOUR_WHITE
    else
        return (self.isOnline) and Nav.COLOUR_NORMAL or Nav.COLOUR_DISABLED
    end
end

function PlayerNode:GetIconColour()
    if self.isFriend then
        return Nav.COLOUR_FRIEND
    elseif self.isGroupmate then
        return Nav.COLOUR_WHITE
    else
        return Nav.COLOUR_NORMAL
    end
end

function PlayerNode:GetSuffixColour()
    return self.canJumpToPlayer and Nav.COLOUR_JUMPABLE or Nav.COLOUR_SUFFIX_NORMAL
end

function PlayerNode:JumpToPrimaryResidence()
    ZO_WorldMap_HideWorldMap()
    ZO_Alert(UI_ALERT_CATEGORY_ALERT, SOUNDS.POSITIVE_CLICK,zo_strformat(GetString(NAVIGATOR_TRAVELING_TO_PLAYER_HOUSE), self.userID))
    JumpToHouse(self.userID)
end

function PlayerNode:JumpToPlayer()
    ZO_Alert(UI_ALERT_CATEGORY_ALERT, SOUNDS.POSITIVE_CLICK,zo_strformat(GetString(NAVIGATOR_TRAVELING_TO_PLAYER_IN_ZONE), self.userID, self.zoneName))
    ZO_WorldMap_HideWorldMap()
    if self.isFriend then
        JumpToFriend(self.userID)
    elseif self.isGuildmate then
        JumpToGuildMember(self.userID)
    elseif self.isGroupmate then
        JumpToGroupMember(self.userID or self.charName)
    end
end

function PlayerNode:DoAction(action)
    if action == Nav.ACTION_TRAVEL then
        self:JumpToPlayer()
    end
end

function PlayerNode:OnSlash() self:JumpToPlayer() end
function PlayerNode:OnEnter() self:JumpToPlayer() end

function PlayerNode:GetActions()
    return { singleClick = Nav.ACTION_TRAVEL }
end

--- @param menu Menu
function PlayerNode:AddMenuItems(menu)
    if self.isOnline then
        menu:AddItem(zo_strformat(GetString(SI_WORLD_MAP_ACTION_TRAVEL_TO_WAYSHRINE), self.userID), function()
            zo_callLater(function() self:JumpToPlayer() end, 10)
        end)
    end
    if Nav.Players:IsGroupLeader() and self.isGroupmate then
        menu:AddItem(GetString(SI_GROUP_LIST_MENU_PROMOTE_TO_LEADER), function()
            GroupPromote(self.unitTag)
            Nav.mainTab.menuOpen = false
            Nav.mainTab:ImmediateRefresh()
        end)
    end
    menu:AddItem(GetString(SI_SOCIAL_MENU_VISIT_HOUSE), function()
        self:JumpToPrimaryResidence()
        Nav.mainTab.menuOpen = false
    end)

    local bookmarkEntry = { playerHouse = self.userID }
    if not Nav.Bookmarks:contains(bookmarkEntry) then
        menu:AddItem(GetString(NAVIGATOR_MENU_ADDHOUSEBOOKMARK), function()
            Nav.Bookmarks:add(bookmarkEntry)
            Nav.mainTab.menuOpen = false
            zo_callLater(function() Nav.mainTab:ImmediateRefresh() end, 10)
        end)
    end
end


--- @class ZoneNode
local ZoneNode = Node:New()

function ZoneNode:GetWeight()
    return Nav.jumpState == Nav.JUMPSTATE_WORLD and 1.0 or 0.9
end

function ZoneNode:GetIcon()
    return "Navigator/media/icons/zone.dds"
end

function ZoneNode:GetActionDescription(action)
    if action == Nav.ACTION_TRAVEL then
        local s = Nav.Utils.EllipsisString(SI_WORLD_MAP_ACTION_TRAVEL_TO_WAYSHRINE)
        if not self:IsJumpable() and Nav.jumpState ~= Nav.JUMPSTATE_WAYSHRINE then
            s = Nav.Utils.StrikethroughString(s)
        end
        return s
    else
        return Node.GetActionDescription(self, action)
    end
end

function ZoneNode:IsJumpable()
    if not CanJumpToPlayerInZone(self.zoneId) or
       self.zoneId <= Nav.ZONE_TAMRIEL or self.zoneId == Nav.ZONE_CYRODIIL then
        return false
    end
    local player = Nav.Players:GetPlayerInZone(self.zoneId)
    return player and true or false
end

function ZoneNode:GetColour()
    local canPort = self:IsJumpable() and Nav.jumpState ~= Nav.JUMPSTATE_TRANSITUS and Nav.jumpState ~= Nav.JUMPSTATE_CYRODIIL
    return (Nav.jumpState == Nav.JUMPSTATE_WAYSHRINE or canPort) and Nav.COLOUR_NORMAL or Nav.COLOUR_POI
end

function ZoneNode:GetTagList()
    local tagList = {}

    if Nav.mainTab.currentView ~= "treasureMaps" and self:IsJumpable() and Nav.jumpState == Nav.JUMPSTATE_WORLD then
        table.insert(tagList, "{player}")
    end

    if self.treasure then
        if Nav.mainTab.currentView == "treasureMaps" then
            local treasureCounts = self.treasure:GetCount(true)
            if treasureCounts.treasure then
                table.insert(tagList, " "..treasureCounts.treasure.."{treasure}")
                treasureCounts.treasure = nil
            end

            for pinType, count in pairs(treasureCounts) do
                table.insert(tagList, " "..count.."{"..pinType.."}")
            end
        else
            local treasureCounts = self.treasure:GetCount(false)
            for pinType, _ in pairs(treasureCounts) do
                table.insert(tagList, "{"..pinType.."}")
            end
        end
    end

    return Nav.Utils.tableConcat(tagList, Node.GetTagList(self))
end

function ZoneNode:JumpToZone()
    Nav.Players:SetupPlayers()
    local zoneId = self.zoneId

    local player = Nav.Players:GetPlayerInZone(zoneId)
    if not player then
        -- Eeek! Refresh the search results and finish
        Nav.mainTab:ImmediateRefresh()
        ZO_Alert(UI_ALERT_CATEGORY_ERROR, SOUNDS.NEGATIVE_CLICK, (zo_strformat(GetString(NAVIGATOR_NO_PLAYER_IN_ZONE), GetZoneNameById(zoneId))))
        return
    end

    ZO_Alert(UI_ALERT_CATEGORY_ALERT, SOUNDS.POSITIVE_CLICK, (zo_strformat(GetString(NAVIGATOR_TRAVELING_TO_ZONE_VIA_PLAYER), player.zoneName, player.userID)))
    ZO_WorldMap_HideWorldMap()
    if player.isFriend then
        JumpToFriend(player.userID)
    elseif player.isGuildmate then
        JumpToGuildMember(player.userID)
    elseif player.isGroupmate then
        JumpToGroupMember(player.userID or player.charName)
    end
end

function ZoneNode:GetActions()
    return Nav.saved.zoneActions
end

function ZoneNode:DoAction(action)
    if action == Nav.ACTION_SHOWONMAP then
        local mapZoneId = Nav.Locations:getCurrentMapZoneId()
        local currentMapId = GetCurrentMapId()
        local targetMapId = self.mapId or Nav.Locations.GetMapIdByZoneId(self.zoneId)
        --Nav.log("ZoneNode:OnClick: self.zoneId %d self.mapId %d mapZoneId %d mapId %d", self.zoneId, self.mapId or 0, mapZoneId, targetMapId)
        if self.zoneId ~= mapZoneId or (self.mapId and self.mapId ~= currentMapId) then
            if targetMapId then
                -- Delay single click to give time for the double-click to occur
                clickEvent = zo_callLater(function()
                    WORLD_MAP_MANAGER:SetMapById(targetMapId)
                end, 200)
            end
        end
    elseif action == Nav.ACTION_TRAVEL then
        self:JumpToZone()
    end
end

--- @param menu Menu
function ZoneNode:AddMenuItems(menu)
    local targetMapId = self.mapId or Nav.Locations.GetMapIdByZoneId(self.zoneId)
    if targetMapId ~= GetCurrentMapId() then
        menu:AddItem(GetString(NAVIGATOR_MENU_SHOWONMAP), function()
            WORLD_MAP_MANAGER:SetMapById(targetMapId)
        end)
    end

    if Nav.jumpState == Nav.JUMPSTATE_WORLD and self.canJumpToPlayer and self.zoneId ~= Nav.ZONE_CYRODIIL then
        menu:AddItem(zo_strformat(GetString(SI_WORLD_MAP_ACTION_TRAVEL_TO_WAYSHRINE), self.zoneName), function()
            zo_callLater(function() self:JumpToZone() end, 10)
        end)
    end
    self:AddBookmarkMenuItem(menu, { zoneId = self.zoneId, mapId = self.mapId })
end


--- @class JumpToZoneNode
local JumpToZoneNode = ZoneNode:New()
JumpToZoneNode.AddMenuItems = ZoneNode.AddMenuItems

function JumpToZoneNode:GetName()
    if self:IsKnown() then
        return zo_strformat(GetString(NAVIGATOR_TRAVEL_TO_ZONE), self.name)
    else
        return GetString(NAVIGATOR_NO_TRAVEL_PLAYER)
    end
end

function JumpToZoneNode:GetIcon()
    return self:IsKnown() and "Navigator/media/icons/recall.dds" or "esoui/art/crafting/crafting_smithing_notrait.dds"
end

function JumpToZoneNode:GetOverlayIcon()
    return nil, nil
end

function JumpToZoneNode:GetSuffix() return "" end
function JumpToZoneNode:GetTagList() return {} end

function JumpToZoneNode:GetActions()
    return { singleClick = Nav.ACTION_TRAVEL }
end

function JumpToZoneNode:GetActionDescription(_)
    local desc = Nav.Utils.EllipsisString(SI_WORLD_MAP_ACTION_TRAVEL_TO_WAYSHRINE)
    return desc
end

function JumpToZoneNode:GetColour(isSelected)
    if isSelected and self:IsKnown() then
        return Nav.COLOUR_WHITE
    else
        return self:IsKnown() and Nav.COLOUR_NORMAL or Nav.COLOUR_DISABLED
    end
end

JumpToZoneNode.GetIconColour = JumpToZoneNode.GetColour

function JumpToZoneNode:DoAction(action)
    if action == Nav.ACTION_TRAVEL then
        self:JumpToZone()
    else
        Node.DoAction(self, action)
    end
end


--- @class HouseNode
local HouseNode = Node:New()

function HouseNode:IsHouse() return true end

function HouseNode:GetHouseId()
    if self.houseId == nil then
        self.houseId = GetFastTravelNodeHouseId(self.nodeIndex)
    end
    return self.houseId
end

function HouseNode:GetCollectableId()
    if self.collectibleId == null then
        self.collectibleId = GetCollectibleIdForHouse(self:GetHouseId())
    end
    return self.collectibleId
end

function HouseNode:IsOwned()
    return IsCollectibleOwnedByDefId(self:GetCollectableId())
end

function HouseNode:IsPrimary()
    if self.isPrimary == nil then
        self.isPrimary = self:GetHouseId() == GetHousingPrimaryHouse()
    end
    return self.isPrimary
end

function HouseNode:GetWeight()
    local weight = 1.0

    if self.isAlias then
        weight = 0.6
    elseif not self:IsOwned() then
        weight = 0.4
    elseif Nav.Bookmarks:contains(self) then
        weight = 1.2
    end
    if self:IsPrimary() then
        weight = weight + 0.1
    end

    return weight
end

function HouseNode:GetIcon()
    return "Navigator/media/icons/house.dds"
end

function HouseNode:GetActionDescription(action)
    if action == Nav.ACTION_TRAVEL then
        if self:IsOwned() then
            return Nav.Utils.EllipsisString(SI_WORLD_MAP_ACTION_TRAVEL_TO_HOUSE_INSIDE)
        else
            return Nav.Utils.EllipsisString(SI_WORLD_MAP_ACTION_PREVIEW_HOUSE)
        end
    elseif action == Nav.ACTION_TRAVELOUTSIDE then
        local s = Nav.Utils.EllipsisString(SI_WORLD_MAP_ACTION_TRAVEL_TO_HOUSE_OUTSIDE)
        if not self:IsOwned() then
            s = Nav.Utils.StrikethroughString(s)
        end
        return s
    else
        return Node.GetActionDescription(self, action)
    end
end

function HouseNode:GetIconColour()
    if self:IsOwned() then
        return Nav.COLOUR_WHITE
    else
        return Nav.COLOUR_DISABLED
    end
end

function HouseNode:GetOverlayIcon()
    if self:IsPrimary() then
        return "Navigator/media/overlays/star.dds", Nav.COLOUR_WHITE
    else
        return nil, nil
    end
end

function HouseNode:GetColour(isSelected)
    local available = self:IsKnown() and self:IsOwned() and CanJumpToHouseFromCurrentLocation()
    if isSelected and available then
        return Nav.COLOUR_WHITE
    else
        return available and Nav.COLOUR_NORMAL or Nav.COLOUR_DISABLED
    end
end

function HouseNode:GetSuffixColour()
    local available = self:IsKnown() and self:IsOwned() and CanJumpToHouseFromCurrentLocation()
    return available and Nav.COLOUR_SUFFIX_NORMAL or Nav.COLOUR_SUFFIX_DISABLED
end

function HouseNode:Jump(jumpOutside)
    if not CanJumpToHouseFromCurrentLocation() then
        local cannotJumpString = self:IsOwned() and GetString(SI_COLLECTIONS_CANNOT_JUMP_TO_HOUSE_FROM_LOCATION) or GetString(SI_COLLECTIONS_CANNOT_PREVIEW_HOUSE_FROM_LOCATION)
        zo_callLater(function()
            ZO_WorldMap_HideWorldMap()
            ZO_Alert(UI_ALERT_CATEGORY_ERROR, SOUNDS.NEGATIVE_CLICK, cannotJumpString)
        end, 10)
        return
    end

    local stringId = jumpOutside and NAVIGATOR_TRAVELING_TO_HOUSE_OUTSIDE or NAVIGATOR_TRAVELING_TO_HOUSE_INSIDE
    ZO_Alert(UI_ALERT_CATEGORY_ALERT, SOUNDS.POSITIVE_CLICK, zo_strformat(GetString(stringId), self.name))
    RequestJumpToHouse(self:GetHouseId(), jumpOutside)
    zo_callLater(function() ZO_WorldMap_HideWorldMap() end, 10)
end

function HouseNode:GetActions()
    return Nav.saved.houseActions
end

function HouseNode:DoAction(action)
    if action == Nav.ACTION_TRAVELOUTSIDE then
        if self:IsOwned() then
            self:Jump(true)
        else
            ZO_Alert(UI_ALERT_CATEGORY_ERROR, SOUNDS.NEGATIVE_CLICK, SI_JUMPRESULT17)
        end
    else
        Node.DoAction(self, action)
    end
end

--- @param menu Menu
function HouseNode:AddMenuItems(menu)
    if self:IsOwned() then
        menu:AddItem(zo_strformat(GetString(SI_WORLD_MAP_ACTION_TRAVEL_TO_HOUSE_INSIDE), self.name), function()
            self:Jump(false)
        end)
        menu:AddItem(zo_strformat(GetString(SI_WORLD_MAP_ACTION_TRAVEL_TO_HOUSE_OUTSIDE), self.name), function()
            self:Jump(true)
        end)
    else
        menu:AddItem(zo_strformat(GetString(SI_WORLD_MAP_ACTION_PREVIEW_HOUSE), self.name), function()
            self:Jump(false)
        end)
    end
    --TODO: Revisit: setting the primary residence didn't seem to be immediately visible
    --if not data.isPrimary then
    --    AddMenuItem(zo_strformat(GetString(SI_HOUSING_FURNITURE_SETTINGS_GENERAL_PRIMARY_RESIDENCE_BUTTON_TEXT), data.name), function()
    --        local houseId = data.houseId or GetFastTravelNodeHouseId(data.nodeIndex)
    --        SetHousingPrimaryHouse(houseId)
    --        zo_callLater(function()
    --            Nav.Locations:SetupNodes()
    --            Nav.mainTab:ImmediateRefresh()
    --        end, 10)
    --        ClearMenu()
    --    end)
    --end
    menu:AddItem(GetString(NAVIGATOR_MENU_SHOWONMAP), function()
        self:ZoomToPOI(false)
    end)
    menu:AddItem(GetString(NAVIGATOR_MENU_SETDESTINATION), function()
        self:ZoomToPOI(true)
    end)
    self:AddBookmarkMenuItem(menu, { nodeIndex = self.nodeIndex })
end


--- @class FastTravelNode
local FastTravelNode = Node:New()

function FastTravelNode:GetWeight()
    local weight = ((self.freeRecall or Nav.jumpState == Nav.JUMPSTATE_WAYSHRINE) and 1.0) or
            (not self:IsKnown() and 0.4) or
            (self.disabled and 0.3) or 0.8

    if Nav.Bookmarks:contains(self) then
        weight = weight + 0.15
    end
    if self.traders and self.traders > 0 then
        weight = weight + 0.02 * self.traders
    end

    return weight
end

function FastTravelNode:GetSuffix()
    if self.poiType == Nav.POI_GROUP_DUNGEON then
        return self.nodeIndex ~= 550 and GetString(NAVIGATOR_DUNGEON) or ""
    elseif self.poiType == Nav.POI_TRIAL then
        return GetString(NAVIGATOR_TRIAL)
    elseif self.poiType == Nav.POI_ARENA then
        return GetString(NAVIGATOR_ARENA)
    elseif Nav.mainTab.currentView == "guildTraders" and self.traders > 0 then
        return "  "..self.traders
    end
    return ""
end

function FastTravelNode:GetColour(isSelected)
    local available = Nav.jumpState ~= Nav.JUMPSTATE_TRANSITUS and Nav.jumpState ~= Nav.JUMPSTATE_CYRODIIL
    if isSelected and available then
        return Nav.COLOUR_WHITE
    else
        return (available) and Nav.COLOUR_NORMAL or Nav.COLOUR_DISABLED
    end
end

function FastTravelNode:GetSuffixColour()
    local available = Nav.jumpState ~= Nav.JUMPSTATE_TRANSITUS and Nav.jumpState ~= Nav.JUMPSTATE_CYRODIIL
    return (available) and Nav.COLOUR_SUFFIX_NORMAL or Nav.COLOUR_SUFFIX_DISABLED
end


function FastTravelNode:GetTagList()
    local tagList = {}

    if self.traders and self.traders > 0 then
        if Nav.mainTab.currentView ~= "guildTraders" then
            if self.traders >= 5 then
                table.insert(tagList, "{city}")
            elseif self.traders >= 2 then
                table.insert(tagList, "{town}")
            end
        end
        table.insert(tagList, "{trader}")
    end

    return Nav.Utils.tableConcat(tagList, Node.GetTagList(self))
end

function FastTravelNode:GetOverlayIcon()
    if self:IsKnown() and self:GetRecallCost() then
        return "Navigator/media/overlays/coin.dds", Nav.COLOUR_COIN
    else
        return nil, nil
    end
end

function FastTravelNode:GetRecallCost()
    if Nav.jumpState == Nav.JUMPSTATE_WAYSHRINE or self.disabled then
        return nil
    end

    local _, timeLeft = GetRecallCooldown()
    if timeLeft == 0 then
        local currencyAmount = GetRecallCost(self.nodeIndex)
        if currencyAmount > 0 then
            return currencyAmount
        end
    end
    return nil -- It's free!
end

---TODO: Convert FastTravelNode:GetTooltip into Nav.Tooltip
function FastTravelNode:GetTooltip(control)
    -- Converted from ESOUI: InformationTooltipMixin:AppendWayshrineTooltip(pin)
    local nodeIndex = self.nodeIndex
    local informationTooltip = Node.GetTooltip(self, control, name)

    if self.traders and self.traders > 0 then
        informationTooltip:AddLine(zo_strformat(GetString(NAVIGATOR_TOOLTIP_GUILDTRADERS), self.traders), "", ZO_NORMAL_TEXT:UnpackRGB())
    end

    local isOutboundOnly, outboundOnlyErrorStringId = GetFastTravelNodeOutboundOnlyInfo(nodeIndex)
    if Nav.currentNodeIndex == nodeIndex then --NO CLICK: Can't travel to origin
        informationTooltip:AddLine(GetString(SI_TOOLTIP_WAYSHRINE_CURRENT_LOC), "", ZO_HIGHLIGHT_TEXT:UnpackRGB())
    elseif Nav.currentNodeIndex == nil and IsInCampaign() then --NO CLICK: Can't recall while inside AvA zone
        informationTooltip:AddLine(GetString(SI_TOOLTIP_WAYSHRINE_CANT_RECALL_AVA), "", ZO_ERROR_COLOR:UnpackRGB())
    elseif isOutboundOnly then --NO CLICK: Can't travel to this wayshrine, only from it
        local message = GetErrorString(outboundOnlyErrorStringId)
        informationTooltip:AddLine(message, "", ZO_ERROR_COLOR:UnpackRGB())
    elseif not CanLeaveCurrentLocationViaTeleport() then --NO CLICK: Current Zone or Subzone restricts jumping
        local cantLeaveStringId
        if IsInOutlawZone() then
            cantLeaveStringId = SI_TOOLTIP_WAYSHRINE_CANT_RECALL_OUTLAW_REFUGE
        else
            cantLeaveStringId = SI_TOOLTIP_WAYSHRINE_CANT_RECALL_FROM_LOCATION
        end
        informationTooltip:AddLine(GetString(cantLeaveStringId), "", ZO_ERROR_COLOR:UnpackRGB())
        --elseif pin:IsLockedByLinkedCollectible() then --CLICK: Open the store
        --    local r, g, b = GetInterfaceColor(INTERFACE_COLOR_TYPE_MARKET_COLORS, MARKET_COLORS_ON_SALE)
        --    local SET_TO_FULL_SIZE = true
        --    informationTooltip:AddLine(ZO_WorldMap_GetWayshrineTooltipCollectibleLockedText(pin), "", r, g, b, CENTER, MODIFY_TEXT_TYPE_NONE, TEXT_ALIGN_CENTER, SET_TO_FULL_SIZE)
        --
        --    if pin:GetLinkedCollectibleType() == COLLECTIBLE_CATEGORY_TYPE_CHAPTER then
        --        informationTooltip:AddLine(GetString(SI_TOOLTIP_WAYSHRINE_CLICK_TO_UPGRADE_CHAPTER), "", ZO_HIGHLIGHT_TEXT:UnpackRGB())
        --    else
        --        informationTooltip:AddLine(GetString(SI_TOOLTIP_WAYSHRINE_CLICK_TO_OPEN_CROWN_STORE), "", ZO_HIGHLIGHT_TEXT:UnpackRGB())
        --    end
    elseif IsUnitDead("player") then --NO CLICK: Dead
        informationTooltip:AddLine(GetString(SI_TOOLTIP_WAYSHRINE_CANT_RECALL_WHEN_DEAD), "", ZO_ERROR_COLOR:UnpackRGB())
    else
        self:AddTooltipActions(informationTooltip)
    end

    return informationTooltip
end

function FastTravelNode:Jump()
    if not self:IsKnown() or self.disabled then
        Nav.log("FastTravelNode:Jump: unknown or disabled")
        return
    end

    ZO_Dialogs_ReleaseDialog("FAST_TRAVEL_CONFIRM")
    ZO_Dialogs_ReleaseDialog("RECALL_CONFIRM")

    if Nav.jumpState == Nav.JUMPSTATE_WORLD then
        -- Locked out of recall for a time
        local _, timeLeft = GetRecallCooldown()
        if timeLeft ~= 0 then
            local text = zo_strformat(SI_FAST_TRAVEL_RECALL_COOLDOWN, self.originalName, ZO_FormatTimeMilliseconds(timeLeft, TIME_FORMAT_STYLE_DESCRIPTIVE, TIME_FORMAT_PRECISION_SECONDS))
            ZO_Alert(UI_ALERT_CATEGORY_ERROR, SOUNDS.NEGATIVE_CLICK, text)
            return
        end
    end

    local confirm = Nav.saved.confirmFastTravel
    local cost = Nav.jumpState == Nav.JUMPSTATE_WORLD and GetRecallCost(self.nodeIndex) or 0
    local currency = GetRecallCurrency(self.nodeIndex)
    local canAffordRecall = cost <= GetCurrencyAmount(currency, CURRENCY_LOCATION_CHARACTER)
    if (confirm == Nav.CONFIRMFASTTRAVEL_NEVER and canAffordRecall) or
       (confirm == Nav.CONFIRMFASTTRAVEL_WHENCOST and cost == 0) then
        zo_callLater(function()
            FastTravelToNode(self.nodeIndex)
            ZO_WorldMap_HideWorldMap()
            local id = Nav.jumpState == Nav.JUMPSTATE_WORLD and NAVIGATOR_RECALLING_TO_LOCATION_COST or NAVIGATOR_TRAVELING_TO_LOCATION
            local currencyString = zo_strformat(SI_NUMBER_FORMAT, ZO_Currency_FormatKeyboard(CURT_MONEY, cost, ZO_CURRENCY_FORMAT_AMOUNT_ICON))
            ZO_Alert(UI_ALERT_CATEGORY_ALERT, SOUNDS.POSITIVE_CLICK,
                    zo_strformat(GetString(id), self.name, currencyString))
            Nav.Recents:insert(self.nodeIndex)
        end, 10)
        return
    end

    local id = Nav.jumpState == Nav.JUMPSTATE_WORLD and "RECALL_CONFIRM" or "FAST_TRAVEL_CONFIRM"
    ZO_Dialogs_ShowPlatformDialog(id, {nodeIndex = self.nodeIndex}, {mainTextParams = {self.originalName}})
end

--- @param menu Menu
function FastTravelNode:AddMenuItems(menu)
    if self:IsKnown() then
        local strId = Nav.jumpState == Nav.JUMPSTATE_WORLD and SI_WORLD_MAP_ACTION_RECALL_TO_WAYSHRINE or SI_WORLD_MAP_ACTION_TRAVEL_TO_WAYSHRINE
        menu:AddItem(zo_strformat(GetString(strId), self.name), function()
            self:Jump()
        end)
    end
    menu:AddItem(GetString(NAVIGATOR_MENU_SHOWONMAP), function()
        self:ZoomToPOI(false)
    end)
    menu:AddItem(GetString(NAVIGATOR_MENU_SETDESTINATION), function()
        self:ZoomToPOI(true)
    end)
    self:AddBookmarkMenuItem(menu, { nodeIndex = self.nodeIndex })
end

function FastTravelNode:GetActions()
    return Nav.saved.destinationActions
end


--- @class PlayerHouseNode
local PlayerHouseNode = Node:New()

function PlayerHouseNode:GetIcon()
    return "Navigator/media/icons/house.dds"
end

function PlayerHouseNode:GetOverlayIcon()
    return "Navigator/media/overlays/player.dds", Nav.COLOUR_WHITE
end

function PlayerHouseNode:GetColour(isSelected)
    if isSelected and CanJumpToHouseFromCurrentLocation() then
        return Nav.COLOUR_WHITE
    else
        return CanJumpToHouseFromCurrentLocation() and Nav.COLOUR_NORMAL or Nav.COLOUR_DISABLED
    end
end

function PlayerHouseNode:GetSuffixColour()
    return CanJumpToHouseFromCurrentLocation() and Nav.COLOUR_SUFFIX_NORMAL or Nav.COLOUR_SUFFIX_DISABLED
end

function PlayerHouseNode:GetActions()
    return { singleClick = Nav.ACTION_VISITHOUSE }
end

function PlayerHouseNode:DoAction(action)
    if action == Nav.ACTION_VISITHOUSE then
        ZO_WorldMap_HideWorldMap()
        ZO_Alert(UI_ALERT_CATEGORY_ALERT, SOUNDS.POSITIVE_CLICK,zo_strformat(GetString(NAVIGATOR_TRAVELING_TO_PLAYER_HOUSE), self.userID))
        JumpToHouse(self.userID)
    else
        Node.DoAction(self, action)
    end
end


--- @param menu Menu
function PlayerHouseNode:AddMenuItems(menu)
    menu:AddItem(GetString(SI_SOCIAL_MENU_VISIT_HOUSE), function()
        zo_callLater(function()
            ZO_WorldMap_HideWorldMap()
            ZO_Alert(UI_ALERT_CATEGORY_ALERT, SOUNDS.POSITIVE_CLICK,zo_strformat(GetString(NAVIGATOR_TRAVELING_TO_PLAYER_HOUSE), self.userID))
            JumpToHouse(self.userID)
        end, 10)
    end)
end


--- @class POINode
local POINode = Node:New()

function POINode:IsPOI() return true end

function POINode:GetColour(isSelected)
    if isSelected and self:IsKnown() and not self.disabled then
        return Nav.COLOUR_WHITE
    elseif self:IsKnown() and not self.disabled then
        return Nav.COLOUR_POI
    else
        return Nav.COLOUR_DISABLED
    end
end

function POINode:GetSuffixColour()
    if self:IsKnown() and not self.disabled then
        return Nav.COLOUR_SUFFIX_POI
    else
        return Nav.COLOUR_SUFFIX_DISABLED
    end
end
POINode.GetTagColour = POINode.GetSuffixColour

--- @param menu Menu
function POINode:AddMenuItems(menu)
    menu:AddItem(GetString(NAVIGATOR_MENU_SHOWONMAP), function()
        self:ZoomToPOI(false)
    end)
    menu:AddItem(GetString(NAVIGATOR_MENU_SETDESTINATION), function()
        self:ZoomToPOI(true)
    end)
    self:AddBookmarkMenuItem(menu, { poi = { poiIndex = self.poiIndex, zoneId = self.zoneId } })
end

function POINode:GetActions()
    return Nav.saved.poiActions
end

function POINode:GetWeight()
    local weight = self:IsKnown() and 0.5 or 0.3
    if Nav.Bookmarks:contains(self) then
        weight = weight + 0.05
    end
    return weight
end


--- @class KeepNode
local KeepNode = Node:New()

function KeepNode:GetSuffix()
    return Nav.KeepSuffix(self.originalName)
end

function KeepNode:GetColour(isSelected)
    if self.accessible then
        return isSelected and Nav.COLOUR_WHITE or Nav.COLOUR_NORMAL
    else
        return Nav.COLOUR_POI
    end
end

function KeepNode:GetSuffixColour()
    return self.accessible and  Nav.COLOUR_SUFFIX_NORMAL or Nav.COLOUR_SUFFIX_POI
end

function KeepNode:GetTagList()
    local tagList = {}

    local isUnderAttack = self:IsUnderAttack()
    if isUnderAttack then
        --Nav.log("Keep %s %d UA %d", self.name, self.keepId, isUnderAttack)
        table.insert(tagList, isUnderAttack == 2 and "{attackburst}" or "{attackburst-small}")
    end

    return Nav.Utils.tableConcat(tagList, Node.GetTagList(self))
end

function KeepNode:GetTagColour()
    return Nav.COLOUR_WHITE
end

function KeepNode:IsUnderAttack()
    local historyPercent = ZO_WorldMap_GetHistoryPercentToUse()
    if GetHistoricalKeepUnderAttack(self.keepId, self.bgContext, historyPercent) then
        return 2
    end

    for i = 1, 3 do
        local resourceKeepId = GetResourceKeepForKeep(self.keepId, i)
        if resourceKeepId > 0 then
            -- Check if the resource is being attacked rather than reclaimed
            if GetHistoricalKeepUnderAttack(resourceKeepId, self.bgContext, historyPercent) then
               --and GetKeepAlliance(resourceKeepId, bgContext) == self.alliance then
                return 1
            end
        end
    end

    return nil
end

function KeepNode:GetMapInfo(_, _)
    local _,nx,ny  = GetKeepPinInfo(self.keepId, self.bgContext)
    Nav.log("KeepNode:GetMapInfo: keepId=%d -> %f,%f", self.keepId, nx, ny)
    return nx,ny
end

function KeepNode:Jump()
    local canTravelToKeep = WORLD_MAP_MANAGER:IsInMode(MAP_MODE_AVA_KEEP_RECALL)
    if not canTravelToKeep then
        local startKeepId = GetKeepFastTravelInteraction()
        canTravelToKeep = startKeepId and self.keepId ~= startKeepId
    end
    if canTravelToKeep then
        TravelToKeep(self.keepId)
        ZO_WorldMap_HideWorldMap()
    end
end

--- @param menu Menu
function KeepNode:AddMenuItems(menu)
    if self.accessible then
        menu:AddItem(zo_strformat(GetString(SI_WORLD_MAP_ACTION_TRAVEL_TO_WAYSHRINE), self.name), function()
            self:Jump()
        end)
    end
    menu:AddItem(GetString(NAVIGATOR_MENU_SHOWONMAP), function()
        self:ZoomToPOI(false, true)
    end)
    menu:AddItem(GetString(NAVIGATOR_MENU_SETDESTINATION), function()
        self:ZoomToPOI(true, true)
    end)
    --self:AddBookmarkMenuItem({ nodeIndex = self.nodeIndex })
end

function KeepNode:GetActions()
    return Nav.saved.destinationActions
end

function KeepNode:DoAction(action)
    if not self.accessible and action == Nav.ACTION_TRAVEL then
        action = Nav.ACTION_SETDESTINATION
    end
    if action == Nav.ACTION_SHOWONMAP then
        self:ZoomToPOI(false, true)
    elseif action == Nav.ACTION_SETDESTINATION then
        self:ZoomToPOI(true, true)
    elseif action == Nav.ACTION_TRAVEL then
        self:Jump()
    end
end

function KeepNode:GetWeight()
    local w = (self.icon:find("AvA_borderKeep") and 1.07) or
              (self.icon:find("AvA_town") and 1.08) or
              (self.icon:find("AvA_outpost") and 1.09) or 1.1
    if not self.accessible then w = w - 0.5 end
    return w
end

Nav.PlayerNode = PlayerNode
Nav.ZoneNode = ZoneNode
Nav.JumpToZoneNode = JumpToZoneNode
Nav.HouseNode = HouseNode
Nav.FastTravelNode = FastTravelNode
Nav.PlayerHouseNode = PlayerHouseNode
Nav.POINode = POINode
Nav.KeepNode = KeepNode