---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by david.
--- DateTime: 31/01/2025 12:30
---
local Nav = Navigator
local Players = Nav.Players or {
    players = nil
}
local Utils = Nav.Utils

local function addPlayer(self, zones, zoneId, zoneName, userID, charName, isOnline)
    if self.players[userID] then
        return self.players[userID]
    end

    local player = Nav.PlayerNode:New({
        name = userID,
        zoneId = zoneId,
        zoneName = Utils.FormatSimpleName(zoneName),
        userID = userID,
        known = true,
        canJumpToPlayer = zones[zoneId] and zones[zoneId].canJumpToPlayer,
        isOnline = isOnline
    })

    self.players[userID] = player
    if charName then
        charName = zo_strformat("<<!AC:1>>", charName)
        player.charName = charName
    end
    return player
end

function Players:SetupPlayers()
    local zones = Nav.Locations:GetZones()
    local playerUserID = GetUnitDisplayName("player")

    self.players = {}

    local guildCount = GetNumGuilds()
    for guild = 1, guildCount do
        local guildID = GetGuildId(guild)
        local guildMembers = GetNumGuildMembers(guildID)

        for i = 1, guildMembers do
            local userID, _, _, playerStatus, secsSinceLogoff = GetGuildMemberInfo(guildID, i)

            if userID ~= playerUserID then
                local hasChar, charName, zoneName, _, _, _, _, zoneId = GetGuildMemberCharacterInfo(guildID, i)
                if hasChar then
                    local player = addPlayer(self, zones, zoneId, zoneName, userID, charName, playerStatus ~= PLAYER_STATUS_OFFLINE and secsSinceLogoff == 0)
                    player.guildID = guild
                    player.isGuildmate = true
                end
            end
        end
    end

    local friendCount = GetNumFriends()
    for i = 1, friendCount do
        local userID, _, playerStatus, secsSinceLogoff = GetFriendInfo(i)

        if userID ~= playerUserID then
            local hasChar, charName, zoneName, _, _, _, _, zoneId = GetFriendCharacterInfo(i)
            if hasChar then
                local player = addPlayer(self, zones, zoneId, zoneName, userID, charName, playerStatus ~= PLAYER_STATUS_OFFLINE and secsSinceLogoff == 0)
                player.friendIndex = i
                player.isFriend = true
            end
        end
    end

    local groupCount = GetGroupSize()
    for i = 1, groupCount do
        local unitTag = GetGroupUnitTagByIndex(i)
        if unitTag then
            local charName = GetUnitName(unitTag)
            local userID = GetUnitDisplayName(unitTag)
            if userID ~= playerUserID then
                local zoneId = GetZoneId(GetUnitZoneIndex(unitTag))
                local zoneName = GetZoneNameById(zoneId)
                local player = addPlayer(self, zones, zoneId, zoneName, userID or '"'..charName..'"', charName, IsUnitOnline(unitTag))
                if player then
                    player.isGroupmate = true
                    player.canJumpToPlayer = true
                    player.unitTag = unitTag
                    player.isLeader = IsUnitGroupLeader(unitTag)
                end
            end
        end
    end
end

function Players:ClearPlayers()
    self.players = nil
end

function Players:UpdatePlayer(userID)
    if not self.players then return end
    if userID == GetUnitDisplayName("player") then return end

    local player = self.players[userID]
    if not player then
        Nav.logWarning("Players:UpdatePlayer: can't find '%s'", userID)
        self:ClearPlayers()
        return
    end

    if player.isFriend then
        local hasChar, _, zoneName, _, _, _, _, zoneId = GetFriendCharacterInfo(player.friendIndex)
        player.zoneName = zoneName
        player.zoneId = zoneId
        player.isOnline = hasChar
    elseif player.isGuildmate then
        local i = GetGuildMemberIndexFromDisplayName(player.guildID, userID)
        local hasChar, _, zoneName, _, _, _, _, zoneId = GetGuildMemberCharacterInfo(player.guildID, i)
        player.zoneName = zoneName
        player.zoneId = zoneId
        player.isOnline = hasChar
    elseif player.isGroupmate then
        if player.unitTag then
            local zoneId = GetZoneId(GetUnitZoneIndex(player.unitTag))
            player.zoneId = zoneId
            player.zoneName = GetZoneNameById(zoneId)
            player.isOnline = IsUnitOnline(player.unitTag)
        end
    end
end

function Players:GetPlayerList(includeOffline)
    if self.players == nil then self:SetupPlayers() end

    local nodes = {}
    for _, player in pairs(self.players) do
        if includeOffline or player.isOnline then
            table.insert(nodes, player)
        end
    end

    return nodes
end

function Players:GetPlayerInZone(zoneId)
    if self.players == nil then self:SetupPlayers() end

    local players = {}
    for _, player in pairs(self.players) do
        if player.zoneId == zoneId and player.isOnline then
            table.insert(players, player) --return player
        end
    end

    if #players > 0 then
        return players[math.random(#players)]
    else
        return nil
    end
end

function Players.GroupComparison(x, y)
    if x.isLeader and not y.isLeader then -- There can be only one
        return true
    elseif y.isLeader and not x.isLeader then
        return false
    end
    if x.isOnline ~= y.isOnline then
        return (x.isOnline and 1 or 0) > (y.isOnline and 1 or 0)
    end
    return x.name < y.name
end

function Players:GetGroupList()
    if self.players == nil then self:SetupPlayers() end
    
    local list = {}
    for _, player in pairs(self.players) do
        if player.isGroupmate and player.userID then
            table.insert(list, player)
        end
    end

    table.sort(list, Nav.Players.GroupComparison)

    return list
end

function Players:IsGroupLeader()
    return string.lower(GetUnitName("player")) == string.lower(GetGroupLeaderUnitTag())
end

Nav.Players = Players