---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by david.
--- DateTime: 24/02/2025 07:29
---

local Nav = Navigator


--- @class ViewManager
--- @field views table Map of Views, keyed on their id
local ViewManager = Nav.ViewManager or {
    views = {},
    menuList = {}
}

--- @usage Add a View to the ViewManager, but don't add it to the Views menu
--- @param view View The view to add
function ViewManager:Add(view)
    self.views[view.id] = view
    --table.insert(self.list, view)
end

--- @usage Add a View to the ViewManager and the Views menu
--- @param view View The view to add
function ViewManager:AddToMenu(view)
    self.views[view.id] = view
    table.insert(self.menuList, view)
end

--- @usage Get the list of Views to display in the Views menu
--- @return table List of Views
function ViewManager:GetMenuViews()
    return self.menuList
end

function ViewManager:NewView(id)
    return self.views[id]
end

--- @usage Run and return the appropriate View's Build method, optionally filtering by a search term
--- @param searchString string|nil The current string to filter by
--- @param viewId string|nil The current View's id
--- @param zone Node The zone object for the current map
---
function ViewManager:Build(searchString, viewId, zone)
    local isSearching = (searchString and searchString ~= "")

    if not viewId or not self.views[viewId] then
        if isSearching then
            viewId = "search"
        elseif IsInGamepadPreferredMode() then
            if zone and zone.zoneId == Nav.ZONE_CYRODIIL then
                viewId = "cyrodiil"
            else
                viewId = "standard"
            end
        else
            if zone then
                if zone.zoneId == Nav.ZONE_TAMRIEL then
                    viewId = "tamriel"
                elseif zone.zoneId == Nav.ZONE_CYRODIIL then
                    viewId = "cyrodiil"
                else
                    viewId = "zone"
                end
            else
                viewId = "standard"
            end
        end
    end

    local view = self.views[viewId]:New()

    if not view then
        view = self.views["tamriel"]:New()
        Nav.logWarning("View:Build: no content chosen for viewId = '%s'", viewId)
    end

    local context = {
        isSearching = isSearching,
        searchString = searchString,
        zone = zone
    }

    local categoryList = view:Build(context)

    if isSearching then
        Nav.Search:FilterView(categoryList, searchString)
    end

    return categoryList
end


--- @class View
local View = {}

function View:New(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self
    return o
end

function View:IsAvailable() return true end

function View:AddGroupCategory(categoryList)
    local group = Nav.Players:GetGroupList()
    if #group > 0 then
        table.sort(group, Nav.Players.GroupComparison)
        table.insert(categoryList, {
            id = "group",
            title = SI_MAIN_MENU_GROUP,
            list = group
        })
    end
end

function View:AddBookmarksCategory(categoryList)
    table.insert(categoryList, {
        id = "bookmarks",
        title = NAVIGATOR_CATEGORY_BOOKMARKS,
        list = Nav.Bookmarks:getBookmarks(),
        emptyHint = IsInGamepadPreferredMode()
                        and NAVIGATOR_HINT_NOBOOKMARKS_GAMEPAD
                         or NAVIGATOR_HINT_NOBOOKMARKS
    })
end

function View:AddRecentsCategory(categoryList)
    local recentCount = Nav.saved.recentsCount
    if recentCount > 0 then
        table.insert(categoryList, {
            id = "recents",
            title = NAVIGATOR_CATEGORY_RECENT,
            list = Nav.Recents:getRecents(),
            emptyHint = NAVIGATOR_HINT_NORECENTS,
            maxEntries = recentCount
        })
    end
end

function View:AddZoneCategory(categoryList, zone)
    local list = Nav.Locations:GetNodeList(zone.zoneId, false, Nav.saved.listPOIs)
    table.sort(list, Nav.Node.WeightComparison)

    if Nav.jumpState == Nav.JUMPSTATE_WORLD and zone.zoneId ~= Nav.ZONE_CYRODIIL and
       zone.zoneId ~= Nav.ZONE_IMPERIALCITY and zone.zoneId ~= Nav.ZONE_IMPERIALSEWERS then
        local node = Nav.JumpToZoneNode:New(Nav.Utils.shallowCopy(zone))
        local playerInfo = Nav.Players:GetPlayerInZone(zone.zoneId)
        node.known = playerInfo ~= nil
        table.insert(list, 1, node)
    end

    local title = zone.name
    local tagString = zone:CreateTagListString(false, false)
    if tagString then
        title = title .. "  " .. tagString
    end

    table.insert(categoryList, {
        id = "zone",
        title = title,
        list = list
    })
end

function View:AddCyrodiilCategories(categoryList)
    local list = Nav.Locations:GetNodeList(Nav.ZONE_CYRODIIL, false, Nav.saved.listPOIs)
    local zone = Nav.Locations.zones[Nav.ZONE_CYRODIIL]

    local allianceNodes = {}
    allianceNodes[ALLIANCE_ALDMERI_DOMINION] = {}
    allianceNodes[ALLIANCE_DAGGERFALL_COVENANT] = {}
    allianceNodes[ALLIANCE_EBONHEART_PACT] = {}
    local poiNodes = {}

    for i = 1, #list do
        local node = list[i]
        if node.alliance and allianceNodes[node.alliance] and
           (not node.icon:find("borderKeep") or node.alliance == Nav.currentAlliance) then
            table.insert(allianceNodes[node.alliance], node)
        elseif node.alliance and not node.icon:find("borderKeep") then
            table.insert(poiNodes, node)
        end
    end

    for _, poiNode in pairs(zone.pois) do
        table.insert(poiNodes, poiNode)
    end

    local pa = Nav.currentAlliance
    local allianceList =
            (pa == ALLIANCE_ALDMERI_DOMINION and { ALLIANCE_ALDMERI_DOMINION, ALLIANCE_DAGGERFALL_COVENANT, ALLIANCE_EBONHEART_PACT }) or
            (pa == ALLIANCE_DAGGERFALL_COVENANT and { ALLIANCE_DAGGERFALL_COVENANT, ALLIANCE_EBONHEART_PACT, ALLIANCE_ALDMERI_DOMINION }) or
            (pa == ALLIANCE_EBONHEART_PACT and { ALLIANCE_EBONHEART_PACT, ALLIANCE_ALDMERI_DOMINION, ALLIANCE_DAGGERFALL_COVENANT })

    for i = 1, #allianceList do
        local alliance = allianceList[i]
        table.sort(allianceNodes[alliance], Nav.Node.WeightComparison)
        table.insert(categoryList, {
            id = string.format("alliance_%d", alliance),
            title = Nav.Utils.FormatSimpleName(GetAllianceName(alliance)),
            list = allianceNodes[alliance]
        })
    end

    table.sort(poiNodes, Nav.Node.WeightComparison)
    table.insert(categoryList, {
        id = "pois",
        title = NAVIGATOR_CATEGORY_POI,
        list = poiNodes
    })
end


--- @class StandardView
local StandardView = View:New({ id = "standard" })

function StandardView:New()
    local o = {}
    setmetatable(o, self)
    self.__index = self
    return o
end

function StandardView:Build()
    local categoryList = {}

    self:AddGroupCategory(categoryList)
    self:AddBookmarksCategory(categoryList)
    self:AddRecentsCategory(categoryList)

    return categoryList
end

ViewManager:Add(StandardView:New())

--- @class ZoneView
local ZoneView = View:New({ id = "zone" })

function ZoneView:Build(context)
    local categoryList = {}

    self:AddGroupCategory(categoryList)
    self:AddBookmarksCategory(categoryList)
    self:AddRecentsCategory(categoryList)
    self:AddZoneCategory(categoryList, context.zone)

    return categoryList
end

ViewManager:Add(ZoneView:New())


--- @class CyrodiilView
local CyrodiilView = View:New({ id = "cyrodiil" })

function CyrodiilView:Build()
    local categoryList = {}

    self:AddGroupCategory(categoryList)

    if Nav.jumpState == Nav.JUMPSTATE_WORLD or Nav.jumpState == Nav.JUMPSTATE_WAYSHRINE then
        self:AddBookmarksCategory(categoryList)
        self:AddRecentsCategory(categoryList)
    end

    self:AddCyrodiilCategories(categoryList)

    return categoryList
end

ViewManager:Add(CyrodiilView:New())


---@class SearchView
local SearchView = View:New({ id = "search" })

function SearchView:New(showHidden)
    local o = { showHidden = showHidden }
    setmetatable(o, self)
    self.__index = self
    return o
end

function SearchView:Build()
    local categoryList = {}

    local zoneId = (Nav.jumpState == Nav.JUMPSTATE_TRANSITUS) and Nav.ZONE_CYRODIIL
    local list = Nav.Locations:GetNodeList(zoneId, true)
    if Nav.jumpState ~= Nav.JUMPSTATE_TRANSITUS then
        Nav.Utils.tableConcat(list, Nav.Locations:GetZoneList(true))
    end

    --table.sort(list, Nav.Node.WeightComparison)

    table.insert(categoryList, {
        id = "results",
        title = NAVIGATOR_CATEGORY_RESULTS,
        list = list
    })

    return categoryList
end

ViewManager:Add(SearchView:New())


--- @class TamrielView
local TamrielView = View:New({ id = "tamriel" })

function TamrielView:AddZoneListCategory(categoryList)
    local list = Nav.Locations:GetZoneList()
    table.sort(list, Nav.Utils.NameComparison)

    table.insert(categoryList, {
        id = "zones",
        title = NAVIGATOR_CATEGORY_ZONES,
        list = list
    })
end

function TamrielView:Build()
    local categoryList = {}

    self:AddGroupCategory(categoryList)
    self:AddBookmarksCategory(categoryList)
    self:AddRecentsCategory(categoryList)
    self:AddZoneListCategory(categoryList)

    return categoryList
end

ViewManager:Add(TamrielView:New())


-- == VIEWS MENU VIEWS == --

---@class CurrentZoneView
--- Only shown in gamepad mode
local CurrentZoneView = View:New( {
    id = "currentZone",
    title = function()
        local zone = Nav.Locations:getCurrentMapZone()
        return zone and zone.name or "Current Zone"
    end,
    icon = nil
})

function CurrentZoneView:IsAvailable()
    return IsInGamepadPreferredMode()
end

function CurrentZoneView:Build(context)
    local categoryList = {}
    self:AddZoneCategory(categoryList, context.zone)
    return categoryList
end

ViewManager:AddToMenu(CurrentZoneView:New())

---@class ZonesView
local ZonesView = View:New({
    id = "zones",
    title = NAVIGATOR_SETTINGS_ZONE_ACTIONS_NAME,
    icon = "Navigator/media/icons/zone.dds"
})

function ZonesView:Build()
    local categoryList = {}

    local list = Nav.Locations:GetZoneList()
    table.sort(list, Nav.Node.NameComparison)

    table.insert(categoryList, {
        id = "zones",
        title = NAVIGATOR_SETTINGS_ZONE_ACTIONS_NAME,
        list = list
    })

    return categoryList
end

ViewManager:AddToMenu(ZonesView:New())


---@class PlayersView
local PlayersView = View:New({
    id = "players",
    title = NAVIGATOR_MENU_PLAYERS,
    icon = "Navigator/media/icons/player.dds",
    emptyHint = NAVIGATOR_HINT_NOMATCHES
})

function PlayersView:Build()
    local categoryList = {}
    local list = Nav.Players:GetPlayerList(false)
    table.sort(list, Nav.Node.WeightComparison)

    table.insert(categoryList, {
        id = "players",
        title = NAVIGATOR_MENU_PLAYERS,
        list = list
    })

    return categoryList
end

ViewManager:AddToMenu(PlayersView:New())


---@class HousesView
local HousesView = View:New({
    id = "houses",
    title = NAVIGATOR_SETTINGS_HOUSE_ACTIONS_NAME,
    icon = "Navigator/media/icons/house.dds",
    emptyHint = NAVIGATOR_HINT_NOMATCHES
})

function HousesView:Build(context)
    local categoryList = {}

    local list = Nav.Locations:GetHouseList(context.isSearching)

    local owned = Nav.Utils.GetFilteredArray(list, function(h) return h:IsOwned() end)
    table.sort(owned, Nav.Node.WeightComparison)

    local unowned = Nav.Utils.GetFilteredArray(list, function(h) return not h:IsOwned() end)
    table.sort(unowned, Nav.Node.WeightComparison)

    table.insert(categoryList, {
        id = "houses",
        title = GetString("SI_COLLECTIBLEUNLOCKSTATE", COLLECTIBLE_UNLOCK_STATE_UNLOCKED_OWNED), --NAVIGATOR_SETTINGS_HOUSE_ACTIONS_NAME,
        list = owned
    })

    table.insert(categoryList, {
        id = "houses",
        title = GetString("SI_COLLECTIBLEUNLOCKSTATE", COLLECTIBLE_UNLOCK_STATE_LOCKED), --NAVIGATOR_SETTINGS_HOUSE_ACTIONS_NAME,
        list = unowned
    })

    return categoryList
end

ViewManager:AddToMenu(HousesView:New())


---@class GuildTradersView
local GuildTradersView = View:New({
    id = "guildTraders",
    title = NAVIGATOR_MENU_GUILDTRADERS,
    icon = "Navigator/media/icons/trader.dds"
})

function GuildTradersView:GetTraderNodeList()
    local nodeList = Nav.Locations:GetNodeList(nil, false, false)
    local filteredList = {}

    for i = 1, #nodeList do
        local node = nodeList[i]
        if node.traders and node.traders > 0 then
            table.insert(filteredList, node)
        end
    end

    table.sort(filteredList, Nav.Node.TradersComparison)

    return filteredList
end

function GuildTradersView:Build()
    local categoryList = {}
    local list = self:GetTraderNodeList()
    table.sort(list, Nav.Node.TradersComparison)

    table.insert(categoryList, {
        id = "traders",
        title = NAVIGATOR_MENU_GUILDTRADERS,
        list = list
    })

    return categoryList
end

ViewManager:AddToMenu(GuildTradersView:New())


---@class TreasureMapsView
local TreasureMapsView = View:New({
    id = "treasureMaps",
    title = NAVIGATOR_MENU_TREASUREMAPS_SURVEYS,
    icon = "Navigator/media/icons/map.dds"
})

function TreasureMapsView:GetTreasureMapZoneList(skipZoneId)
    local zones = Nav.Locations:GetZoneList()
    local filteredZones = {}
    for i = 1, #zones do
        local zone = zones[i]
        if zone.treasure and zone.zoneId ~= skipZoneId then
            table.insert(filteredZones, zone)
        end
    end
    table.sort(filteredZones, Nav.Node.NameComparison)
    return filteredZones
end

function TreasureMapsView:GetZoneTreasureMapList(zone)
    if zone.treasure then
        local list = zone.treasure:GetList()
        table.sort(list, Nav.Utils.NameComparison)
        return list
    end
    return { }
end

function TreasureMapsView:Build(context)
    local categoryList = {}

    table.insert(categoryList, {
        id = "otherTreasureMaps",
        title = NAVIGATOR_MENU_TREASUREMAPS_SURVEYS,
        list = self:GetTreasureMapZoneList(),
        emptyHint = NAVIGATOR_HINT_NOMATCHES
    })

    local thisZoneList = self:GetZoneTreasureMapList(context.zone)
    if thisZoneList then
        table.insert(categoryList, {
            id = "zoneTreasureMaps",
            title = context.zone.name,
            list = thisZoneList
        })
    end

    return categoryList
end

function TreasureMapsView:IsAvailable()
    return LibTreasure_GetItemIdData ~= nil
end

ViewManager:AddToMenu(TreasureMapsView:New())


---@class QuestsView

local QuestsView = View:New({
    id = "quests",
    title = NAVIGATOR_MENU_QUESTS,
    icon = "Navigator/media/icons/quest.dds",
    emptyHint = NAVIGATOR_HINT_NOMATCHES
})

function QuestsView:Build()
    return Nav.Quest:BuildQuestCategories()
end

ViewManager:AddToMenu(QuestsView:New())


Nav.ViewManager = ViewManager
