--[[
    Triple Triad ESO - NPC Database
    50 NPCs you can challenge to Triple Triad matches

    NPC structure:
        id          = unique identifier
        name        = NPC name (must match in-game name exactly for targeting)
        zone        = zone where NPC is found
        rank        = difficulty 1-5
        deck        = array of 5 card IDs the NPC uses
        rewardPool  = array of card IDs the NPC can drop on defeat
        dialogue    = flavor text shown when challenging
]]--

local TT = TripleTriadESO

TT.NPCDatabase = {
    -- ═══════════════════════════════════════════
    -- RANK 1 NPCs (Beginner) - 12 NPCs
    -- ═══════════════════════════════════════════
    {
        id = 1,
        name = "Pacrooti",
        zone = "Various (Traveling Merchant)",
        rank = 1,
        deck = { 1, 2, 3, 6, 7 },
        rewardPool = { 6, 7, 8, 9, 10 },
        dialogue = "Pacrooti has many fine cards, yes! But can you beat this one in a game?",
    },
    {
        id = 2,
        name = "Zahra",
        zone = "Vulkhel Guard, Auridon",
        rank = 1,
        deck = { 1, 3, 5, 8, 10 },
        rewardPool = { 5, 8, 10, 11, 12 },
        dialogue = "A card game? How delightful! I was getting bored of guard duty.",
    },
    {
        id = 3,
        name = "Daggerfall Guard",
        zone = "Daggerfall, Glenumbra",
        rank = 1,
        deck = { 2, 4, 6, 7, 9 },
        rewardPool = { 4, 9, 11, 12 },
        dialogue = "I suppose a quick game wouldn't hurt. My shift's almost over anyway.",
    },
    {
        id = 4,
        name = "Thragof",
        zone = "Davon's Watch, Stonefalls",
        rank = 1,
        deck = { 1, 5, 6, 9, 11 },
        rewardPool = { 6, 10, 11, 12 },
        dialogue = "Cards? Thragof crush you at cards like Thragof crush skulls!",
    },
    {
        id = 5,
        name = "Millenith",
        zone = "Fighter's Guild",
        rank = 1,
        deck = { 3, 4, 7, 8, 12 },
        rewardPool = { 7, 8, 11, 12, 13 },
        dialogue = "Training comes in many forms. Let's see your tactical mind.",
    },
    {
        id = 6,
        name = "Felarian",
        zone = "Mages Guild",
        rank = 1,
        deck = { 2, 5, 9, 10, 11 },
        rewardPool = { 9, 10, 11, 13 },
        dialogue = "Ah, a game of wits! Much more civilized than conjuration practice.",
    },
    {
        id = 7,
        name = " Ezabi",
        zone = "Various (Banker)",
        rank = 1,
        deck = { 1, 4, 6, 8, 12 },
        rewardPool = { 6, 8, 12, 13 },
        dialogue = "Ezabi handles your gold and your cards! Shall we play?",
    },
    {
        id = 8,
        name = "Pirharri the Smuggler",
        zone = "Various (Fence)",
        rank = 1,
        deck = { 3, 7, 8, 10, 11 },
        rewardPool = { 7, 10, 11, 14 },
        dialogue = "A card game? Pirharri knows all about hidden values, friend.",
    },
    {
        id = 9,
        name = "Stuga",
        zone = "Daggerfall, Glenumbra",
        rank = 1,
        deck = { 2, 4, 5, 9, 12 },
        rewardPool = { 5, 9, 12, 13 },
        dialogue = "Do you know how long I've been looking for a card opponent?!",
    },
    {
        id = 10,
        name = "Nolmir",
        zone = "Bleakrock Isle",
        rank = 1,
        deck = { 1, 6, 7, 10, 12 },
        rewardPool = { 10, 11, 12, 14 },
        dialogue = "Not much else to do on this frozen rock. Deal the cards.",
    },
    {
        id = 11,
        name = "Gathwen",
        zone = "Khenarthi's Roost",
        rank = 1,
        deck = { 3, 5, 8, 9, 11 },
        rewardPool = { 8, 9, 11, 13 },
        dialogue = "A scholar needs to relax sometimes. Let's play!",
    },
    {
        id = 12,
        name = "Crafty Lerisa",
        zone = "Stros M'Kai",
        rank = 1,
        deck = { 4, 7, 8, 10, 12 },
        rewardPool = { 7, 10, 12, 14 },
        dialogue = "I'm a gambler at heart. You're on, friend!",
    },

    -- ═══════════════════════════════════════════
    -- RANK 2 NPCs (Intermediate) - 12 NPCs
    -- ═══════════════════════════════════════════
    {
        id = 13,
        name = "Naryu Virian",
        zone = "Various (Morag Tong)",
        rank = 2,
        deck = { 13, 15, 18, 21, 23 },
        rewardPool = { 15, 18, 21, 23, 25 },
        dialogue = "I prefer blades to cards, but a Morag Tong always accepts a challenge.",
    },
    {
        id = 14,
        name = "Razum-dar",
        zone = "Various (Auridon/Summerset)",
        rank = 2,
        deck = { 14, 16, 19, 22, 24 },
        rewardPool = { 14, 19, 22, 24, 26 },
        dialogue = "Raz has many talents. Card games are merely one of them.",
    },
    {
        id = 15,
        name = "Jakarn",
        zone = "Various",
        rank = 2,
        deck = { 13, 17, 19, 20, 22 },
        rewardPool = { 17, 19, 20, 22, 25 },
        dialogue = "I never lose. Well, almost never. Alright, sometimes. Let's play!",
    },
    {
        id = 16,
        name = "Darien Gautier",
        zone = "Various (Glenumbra)",
        rank = 2,
        deck = { 15, 16, 18, 21, 24 },
        rewardPool = { 16, 18, 21, 25, 26 },
        dialogue = "A game of cards with a beautiful stranger? Count me in!",
    },
    {
        id = 17,
        name = "Quen",
        zone = "Hew's Bane",
        rank = 2,
        deck = { 14, 17, 20, 23, 24 },
        rewardPool = { 14, 20, 23, 26 },
        dialogue = "I've stolen more valuable things than cards, but let's play.",
    },
    {
        id = 18,
        name = "Eveli Sharp-Arrow",
        zone = "Wrothgar / The Reach",
        rank = 2,
        deck = { 13, 16, 19, 21, 23 },
        rewardPool = { 16, 21, 23, 25 },
        dialogue = "Ooh, cards! I love card games! Is this like the ones in books?",
    },
    {
        id = 19,
        name = "Gabrielle Benele",
        zone = "Various (Mages Guild)",
        rank = 2,
        deck = { 15, 17, 22, 24, 14 },
        rewardPool = { 15, 17, 22, 26, 27 },
        dialogue = "A strategic exercise? My magical mind is well-suited for this.",
    },
    {
        id = 20,
        name = "Kireth Vanos",
        zone = "Various",
        rank = 2,
        deck = { 13, 14, 18, 20, 23 },
        rewardPool = { 13, 18, 20, 25 },
        dialogue = "Raynor won't play with me anymore. You're my new opponent!",
    },
    {
        id = 21,
        name = "Lyranth",
        zone = "Various (Deadlands)",
        rank = 2,
        deck = { 15, 19, 22, 24, 17 },
        rewardPool = { 19, 22, 24, 27, 26 },
        dialogue = "Mortal games amuse me. Very well, I shall indulge you.",
    },
    {
        id = 22,
        name = "Fenn",
        zone = "Rimmen, Northern Elsweyr",
        rank = 2,
        deck = { 14, 16, 20, 21, 24 },
        rewardPool = { 16, 20, 24, 25 },
        dialogue = "A card game? This one's claws are itching for competition!",
    },
    {
        id = 23,
        name = "Fennorian",
        zone = "Western Skyrim",
        rank = 2,
        deck = { 13, 18, 21, 23, 15 },
        rewardPool = { 13, 21, 23, 27 },
        dialogue = "I rarely have time for leisure, but... very well, one game.",
    },
    {
        id = 24,
        name = "Mirri Elendis",
        zone = "Blackwood (Companion)",
        rank = 2,
        deck = { 14, 17, 19, 22, 24 },
        rewardPool = { 17, 19, 22, 26 },
        dialogue = "I'm always up for a game! Just don't expect me to go easy on you.",
    },

    -- ═══════════════════════════════════════════
    -- RANK 3 NPCs (Advanced) - 12 NPCs
    -- ═══════════════════════════════════════════
    {
        id = 25,
        name = "Abnur Tharn",
        zone = "Various",
        rank = 3,
        deck = { 25, 27, 30, 34, 37 },
        rewardPool = { 27, 30, 34, 37, 40 },
        dialogue = "You dare challenge the head of the Elder Council? Amusing.",
    },
    {
        id = 26,
        name = "Sai Sahan",
        zone = "Various",
        rank = 3,
        deck = { 26, 28, 29, 33, 35 },
        rewardPool = { 26, 28, 29, 33, 39 },
        dialogue = "The way of the sword and the way of cards share discipline.",
    },
    {
        id = 27,
        name = "Vanus Galerion",
        zone = "Various (Coldharbour)",
        rank = 3,
        deck = { 27, 31, 33, 34, 38 },
        rewardPool = { 31, 33, 34, 38, 40 },
        dialogue = "The founder of the Mages Guild does not lose at trivial games.",
    },
    {
        id = 28,
        name = "Queen Ayrenn",
        zone = "Vulkhel Guard, Auridon",
        rank = 3,
        deck = { 25, 29, 31, 36, 38 },
        rewardPool = { 29, 31, 36, 38, 41 },
        dialogue = "A Queen must know strategy. Prepare yourself.",
    },
    {
        id = 29,
        name = "Jorunn the Skald-King",
        zone = "Windhelm, Eastmarch",
        rank = 3,
        deck = { 26, 28, 30, 33, 35 },
        rewardPool = { 28, 30, 35, 39, 41 },
        dialogue = "Ha! A game of wits! The Skald-King accepts your challenge!",
    },
    {
        id = 30,
        name = "High King Emeric",
        zone = "Wayrest, Stormhaven",
        rank = 3,
        deck = { 25, 27, 32, 36, 37 },
        rewardPool = { 27, 32, 36, 37, 42 },
        dialogue = "A shrewd game requires a shrewd mind. Let us begin.",
    },
    {
        id = 31,
        name = "Cadwell",
        zone = "Various (Coldharbour/Gold Coast)",
        rank = 3,
        deck = { 26, 30, 32, 34, 36 },
        rewardPool = { 26, 30, 34, 39, 40 },
        dialogue = "Oh splendid! I haven't played cards since I was alive! Or was it after?",
    },
    {
        id = 32,
        name = "The Prophet",
        zone = "The Harborage",
        rank = 3,
        deck = { 28, 29, 31, 35, 37 },
        rewardPool = { 29, 31, 35, 37, 42 },
        dialogue = "Even a blind man can see the wisdom in these cards, Vestige.",
    },
    {
        id = 33,
        name = "Verandis Ravenwatch",
        zone = "Rivenspire / Markarth",
        rank = 3,
        deck = { 25, 30, 33, 36, 38 },
        rewardPool = { 25, 33, 36, 38, 41 },
        dialogue = "I have played games for centuries, mortal. Do try to keep up.",
    },
    {
        id = 34,
        name = "Vastarie",
        zone = "Southern Elsweyr",
        rank = 3,
        deck = { 27, 29, 34, 35, 38 },
        rewardPool = { 27, 34, 35, 38, 43 },
        dialogue = "Knowledge is power, even in games of chance.",
    },
    {
        id = 35,
        name = "Sotha Sil",
        zone = "Clockwork City",
        rank = 3,
        deck = { 26, 31, 33, 37, 28 },
        rewardPool = { 31, 33, 37, 40, 43 },
        dialogue = "Every game is a series of equations. I have already calculated the outcome.",
    },
    {
        id = 36,
        name = "Vivec",
        zone = "Vivec City, Vvardenfell",
        rank = 3,
        deck = { 25, 28, 32, 34, 36 },
        rewardPool = { 28, 32, 34, 36, 42 },
        dialogue = "A warrior-poet finds beauty even in simple card games.",
    },

    -- ═══════════════════════════════════════════
    -- RANK 4 NPCs (Expert) - 8 NPCs
    -- ═══════════════════════════════════════════
    {
        id = 37,
        name = "Mannimarco",
        zone = "The Harborage / Coldharbour",
        rank = 4,
        deck = { 37, 39, 42, 43, 45 },
        rewardPool = { 39, 42, 43, 45 },
        dialogue = "The King of Worms does not play for sport. Only for dominion.",
    },
    {
        id = 38,
        name = "Rada al-Saran",
        zone = "The Reach",
        rank = 4,
        deck = { 38, 40, 41, 44, 46 },
        rewardPool = { 40, 41, 44, 46 },
        dialogue = "I have bested warriors for millennia. A card game is beneath me... yet I accept.",
    },
    {
        id = 39,
        name = "Ithelia",
        zone = "West Weald / The Scholarium",
        rank = 4,
        deck = { 37, 40, 43, 47, 44 },
        rewardPool = { 40, 43, 44, 47 },
        dialogue = "The paths of fate converge here. Your cards cannot save you.",
    },
    {
        id = 40,
        name = "Mephala",
        zone = "Summerset (Artaeum)",
        rank = 4,
        deck = { 38, 41, 42, 45, 47 },
        rewardPool = { 41, 42, 45, 47 },
        dialogue = "Every card you play weaves deeper into my web.",
    },
    {
        id = 41,
        name = "Clavicus Vile",
        zone = "The Deadlands",
        rank = 4,
        deck = { 39, 40, 43, 46, 38 },
        rewardPool = { 39, 43, 46, 48 },
        dialogue = "Let's make a deal — if you win, you get a card. If I win... well.",
    },
    {
        id = 42,
        name = "Nocturnal",
        zone = "Clockwork City / Summerset",
        rank = 4,
        deck = { 37, 41, 44, 47, 42 },
        rewardPool = { 41, 44, 47, 48 },
        dialogue = "In the shadows of uncertainty, I always hold the winning hand.",
    },
    {
        id = 43,
        name = "Hermaeus Mora",
        zone = "Apocrypha / Telvanni Peninsula",
        rank = 4,
        deck = { 38, 40, 43, 45, 44 },
        rewardPool = { 40, 43, 45, 49 },
        dialogue = "All knowledge is mine, mortal. Including the knowledge of your defeat.",
    },
    {
        id = 44,
        name = "Haskill",
        zone = "The Shivering Isles",
        rank = 4,
        deck = { 39, 42, 44, 46, 37 },
        rewardPool = { 42, 44, 46, 49 },
        dialogue = "Lord Sheogorath insists I play. I find it tedious. Shall we begin?",
    },

    -- ═══════════════════════════════════════════
    -- RANK 5 NPCs (Legendary) - 6 NPCs
    -- ═══════════════════════════════════════════
    {
        id = 45,
        name = "Molag Bal",
        zone = "Coldharbour",
        rank = 5,
        deck = { 45, 46, 42, 43, 39 },
        rewardPool = { 45, 50 },
        dialogue = "You would challenge the Lord of Domination? Your audacity amuses me, insect.",
    },
    {
        id = 46,
        name = "Mehrunes Dagon",
        zone = "The Deadlands",
        rank = 5,
        deck = { 46, 45, 41, 43, 40 },
        rewardPool = { 46, 50 },
        dialogue = "The Prince of Destruction shall obliterate your pitiful deck!",
    },
    {
        id = 47,
        name = "Sheogorath",
        zone = "The Shivering Isles",
        rank = 5,
        deck = { 47, 48, 50, 37, 44 },
        rewardPool = { 47, 48, 50 },
        dialogue = "CHEESE! Oh wait, cards? I love cards! Especially the ones that taste like cheese!",
    },
    {
        id = 48,
        name = "Meridia",
        zone = "The Colored Rooms",
        rank = 5,
        deck = { 48, 49, 45, 41, 38 },
        rewardPool = { 48, 49 },
        dialogue = "A mortal dares approach the Lady of Infinite Energies? Play your cards wisely.",
    },
    {
        id = 49,
        name = "Boethiah",
        zone = "Attribution's Share",
        rank = 5,
        deck = { 49, 50, 46, 42, 40 },
        rewardPool = { 49, 50 },
        dialogue = "Deceit and treachery win wars... and card games. Begin.",
    },
    {
        id = 50,
        name = "The Vestige's Shadow",
        zone = "Heart's Grief",
        rank = 5,
        deck = { 50, 48, 47, 45, 43 },
        rewardPool = { 50 },
        dialogue = "I am you, and I am everything you fear. Your own cards turn against you.",
    },
}
