-- COLOR CODES
	-- FFFFFF White (255, 255, 255)
	-- FF3030 Firebrick (255, 48, 48)
	-- CD2626 Firebrick 3 (205, 38, 38)
	-- FFB90F Dark Golden Rod (255, 185, 15)
	-- 7CFC00 Lawn Green (124, 252, 0)
	-- 32CD32 Lime Green (50, 205, 50)
	-- 1E90FF DodgerBlue (30, 144, 255)
	-- C5C29E ZOS Yellow (197, 194, 158)
	-- EAEAEA SGI Gray 92 (234, 234, 234)
	-- 282828 SGI Gray 16 (234, 234, 234)

-- DEFAULT SAVED VARIABLES
RAEIH.DefaultSavedVars =
{
	InfoHubFirstTime = true,
	-- LEGATUS
	EnableLegatus = false,	
	LgtCreateFirstTime = true,

	LockLegatus = false,
	LockLegatusCB = false,

	LegatusAlignment = "Screen-Wide Center",

	LegatusBGType = "Texture",	
	LegatusBGTX = "Glass",
	LegatusBRGB = "282828",
	LegatusBA = 0.7,
	
	LegatusCF = false,
	LegatusSW = true,
	LegatusX = 0,
	LegatusY = 0,
	
	LegatusPadding = 1,

	L1CName = "Empty",
	L2CName = "Empty",
	L3CName = "Empty",
	L4CName = "Empty",
	L5CName = "Empty",
	L6CName = "Empty",
	L7CName = "Empty",
	L8CName = "Empty",
	L9CName = "Empty",
	L10CName = "Empty",
	L11CName = "Empty",
	L12CName = "Empty",
	L13CName = "Empty",
	L14CName = "Empty",
	L15CName = "Empty",
	L16CName = "Empty",
	L17CName = "Empty",
	L18CName = "Empty",
	L19CName = "Empty",
	L20CName = "Empty",

	XL1CName = nil,
	XL2CName = nil,
	XL3CName = nil,
	XL4CName = nil,
	XL5CName = nil,
	XL6CName = nil,
	XL7CName = nil,
	XL8CName = nil,
	XL9CName = nil,
	XL10CName = nil,
	XL11CName = nil,
	XL12CName = nil,
	XL13CName = nil,
	XL14CName = nil,
	XL15CName = nil,
	XL16CName = nil,
	XL17CName = nil,
	XL18CName = nil,
	XL19CName = nil,
	XL20CName = nil,

	-- INFOHUB GENERAL
	InfoHubFont = "Open Sans - Bold",
	InfoHubFontSize = 16,
	InfoHubFontStyle = "Soft Shadow - Thin",
	InfoHubIconW = 32,
	InfoHubIconH = 32,
	InfoHubIconX = 0,
	InfoHubIconY = 0,
	
	InfoHubAHSettingsMenu = false,
	InfoHubAHInteract = true,
	InfoHubAHWorldMap = true,
	InfoHubAHCrafting = true,
	InfoHubAHJournal = true,
	InfoHubAHGamePanels = true,
	InfoHubAHMailbox = true,

	ShowGrid = false,
	GridSize = 65,

	-- OTHERS
	TSFormat = "Point (.)",
	StartTimer = false,
	AnimStage = 0,
	AnimTracker = false,	

	-- FPS
	ShowFPS = false,
	LockFPS = false,
	FPSIconW = 32,
	FPSIconH = 32,
	FPSIconX = 0,
	FPSIconY = 0,
	FPSFont = "Open Sans - Bold",
	FPSFontSize = 16,
	FPSFontStyle = "Soft Shadow - Thin",
	FPSX = 50,
	FPSY = 50,
	FPSDefaultColour = "FFFFFF",	
	FPSAlertColour = "FF3030",		
	FPSWarningColour = "FFB90F",	
	FPSNormalColour = "7CFC00",		
	FPSBA = 0,

	-- LATENCY
	ShowLatency = false,
	LockLatency = false,
	LatencyIconW = 32,
	LatencyIconH = 32,
	LatencyIconX = 0,
	LatencyIconY = 0,
	LatencyFont = "Open Sans - Bold",
	LatencyFontSize = 16,
	LatencyFontStyle = "Soft Shadow - Thin",
	LatencyX = 350,
	LatencyY = 200,
	LatencyDefaultColour = "FFFFFF",	
	LatencyAlertColour = "FF3030",		
	LatencyWarningColour = "FFB90F",	
	LatencyNormalColour = "7CFC00",		
	LatencyBA = 0,	

	-- LUA MEMORY
	ShowLUAMemory = false,
	LockLUAMemory = false,
	LUAMemoryLimit = GetCVar("LuaMemoryLimitMB"),
	LUAMemoryIconW = 32,
	LUAMemoryIconH = 32,
	LUAMemoryIconX = 0,
	LUAMemoryIconY = 0,
	LUAMemoryFont = "Open Sans - Bold",
	LUAMemoryFontSize = 16,
	LUAMemoryFontStyle = "Soft Shadow - Thin",
	LUAMemoryX = 500,
	LUAMemoryY = 200,
	LUAMemoryDefaultColour = "FFFFFF",	
	LUAMemoryAlertColour = "FF3030",		
	LUAMemoryWarningColour = "FFB90F",	
	LUAMemoryNormalColour = "7CFC00",		
	LUAMemoryBA = 0,

	-- TIME
	ShowTime = false,	
	LockTime = false,
	TimeIconW = 32,
	TimeIconH = 32,
	TimeIconX = 0,
	TimeIconY = 0,
	TimeFont = "Open Sans - Bold",
	TimeFontSize = 16,
	TimeFontStyle = "Soft Shadow - Thin",
	TimeX = 150,
	TimeY = 50,
	TimeDefaultColour = "FFFFFF",									
	TimeFormat = "Time",
	Enable12HCF = false,
	TimeBA = 0,
	DateFormat = "MM/DD/YY",

	-- ZONE
	ShowZone = false,
	LockZone = false,
	ZoneFormat = "Subzone",
	ZoneIconW = 32,
	ZoneIconH = 32,
	ZoneIconX = 0,
	ZoneIconY = 0,
	ZoneFont = "Open Sans - Bold",
	ZoneFontSize = 16,
	ZoneFontStyle = "Soft Shadow - Thin",
	ZoneX = 300,
	ZoneY = 50,
	ZoneDefaultColour = "FFFFFF",									
	SubzoneColour = "FFFFFF",										
	ZoneColour = "7CFC00",											
	ZoneBA = 0,
	AWMZ = false,
	WMZLvl = 5,
	ZDone = false,

	-- COORDINATES
	ShowCoordinates = false,
	LockCoordinates = false,
	CoordinatesIconW = 32,
	CoordinatesIconH = 32,
	CoordinatesIconX = 0,
	CoordinatesIconY = 0,
	CoordinatesFont = "Open Sans - Bold",
	CoordinatesFontSize = 16,
	CoordinatesFontStyle = "Soft Shadow - Thin",
	CoordinatesX = 550,
	CoordinatesY = 50,
	CoordinatesDefaultColour = "FFFFFF",							
	CoordinatesXColour = "7CFC00",									
	CoordinatesYColour = "32CD32",									
	CoordinatesBA = 0,

	-- LEVEL & VETERAN RANK
	ShowLVR = false,
	LockLVR = false,
	LVRIconW = 32,
	LVRIconH = 32,
	LVRIconX = 0,
	LVRIconY = 0,
	LVRFont = "Open Sans - Bold",
	LVRFontSize = 16,
	LVRFontStyle = "Soft Shadow - Thin",
	LVRX = 700,
	LVRY = 50,
	LVRDefaultColour = "FFFFFF",									
	LVRColour = "1E90FF",											
	LVRBA = 0,

	-- EXPERIENCE & VETERAN POINTS
	ShowXVP = false,
	LockXVP = false,
	XVPIconW = 32,
	XVPIconH = 32,
	XVPIconX = 0,
	XVPIconY = 0,
	XVPFont = "Open Sans - Bold",
	XVPFontSize = 16,
	XVPFontStyle = "Soft Shadow - Thin",
	XVPX = 800,
	XVPY = 50,
	XVPDefaultColour = "FFFFFF",									
	XVPESColour = "FF3030",											
	XVPMSColour = "FFB90F",											
	XVPLSColour = "7CFC00",											
	XVPFormat = "Current/Max",
	XVPBA = 0,

	-- XVP PER HOUR
	ShowXVPperHour = false,
	LockXVPperHour = false,
	XVPperHourIconW = 32,
	XVPperHourIconH = 32,
	XVPperHourIconX = 0,
	XVPperHourIconY = 0,
	XVPperHourFont = "Open Sans - Bold",
	XVPperHourFontSize = 16,
	XVPperHourFontStyle = "Soft Shadow - Thin",
	XVPperHourX = 900,
	XVPperHourY = 50,
	XVPperHourDefaultColour = "FFFFFF",								
	XVPperHourColour = "1E90FF",									
	XVPperHourBA = 0,

	-- GOLD
	ShowGold = false,
	LockGold = false,
	GoldIconW = 32,
	GoldIconH = 32,
	GoldIconX = 0,
	GoldIconY = 0,
	GoldFont = "Open Sans - Bold",
	GoldFontSize = 16,
	GoldFontStyle = "Soft Shadow - Thin",
	GoldX = 1000,
	GoldY = 50,
	GoldDefaultColour = "FFB90F",									
	GoldBA = 0,

	-- GOLD PER HOUR
	ShowGoldperHour = false,
	LockGoldperHour = false,
	GoldperHourIconW = 32,
	GoldperHourIconH = 32,
	GoldperHourIconX = 0,
	GoldperHourIconY = 0,
	GoldperHourFont = "Open Sans - Bold",
	GoldperHourFontSize = 16,
	GoldperHourFontStyle = "Soft Shadow - Thin",
	GoldperHourX = 1150,
	GoldperHourY = 50,
	GoldperHourDefaultColour = "FFFFFF",							
	GoldperHourColour = "FFB90F",									
	GoldperHourBA = 0,

	-- BANKED GOLD
	ShowBankedGold = false,
	LockBankedGold = false,
	BankedGoldIconW = 32,
	BankedGoldIconH = 32,
	BankedGoldIconX = 0,
	BankedGoldIconY = 0,
	BankedGoldFont = "Open Sans - Bold",
	BankedGoldFontSize = 16,
	BankedGoldFontStyle = "Soft Shadow - Thin",
	BankedGoldX = 1300,
	BankedGoldY = 50,
	BankedGoldDefaultColour = "FFB90F",								
	BankedGoldBA = 0,

	-- DURABILITY
	ShowDurability = false,
	LockDurability = false,
	DurabilityFormat = "General%",
	DurabilityIconW = 32,
	DurabilityIconH = 32,
	DurabilityIconX = 0,
	DurabilityIconY = 0,
	DurabilityFont = "Open Sans - Bold",
	DurabilityFontSize = 16,
	DurabilityFontStyle = "Soft Shadow - Thin",
	DurabilityX = 1450,
	DurabilityY = 50,
	DurabilityDefaultColour = "FFFFFF",								
	DurabilityAlertColour = "FF3030",								
	DurabilityWarningColour = "FFB90F",								
	DurabilityNormalColour = "7CFC00",								
	DurabilityBA = 0,
	AutoRepairEnabled = false,
	AutoRepairThreshold = 25,

	-- REPAIR COST
	ShowRepairCost = false,
	LockRepairCost = false,
	RepairCostIconW = 32,
	RepairCostIconH = 32,
	RepairCostIconX = 0,
	RepairCostIconY = 0,
	RepairCostFont = "Open Sans - Bold",
	RepairCostFontSize = 16,
	RepairCostFontStyle = "Soft Shadow - Thin",
	RepairCostX = 1700,
	RepairCostY = 50,
	RepairCostDefaultColour = "FFFFFF",								
	RepairCostAlertColour = "FF3030",								
	RepairCostWarningColour = "FFB90F",								
	RepairCostNormalColour = "7CFC00",								
	RepairCostBA = 0,

	-- BAG SLOTS
	ShowBagSlots = false,
	LockBagSlots = false,
	BagSlotsFormat = "Used/Total",
	BagSlotsIconW = 32,
	BagSlotsIconH = 32,
	BagSlotsIconX = 0,
	BagSlotsIconY = 0,
	BagSlotsFont = "Open Sans - Bold",
	BagSlotsFontSize = 16,
	BagSlotsFontStyle = "Soft Shadow - Thin",
	BagSlotsX = 50,
	BagSlotsY = 100,
	BagSlotsDefaultColour = "FFFFFF",								
	BagSlotsAlertColour = "FF3030",									
	BagSlotsWarningColour = "FFB90F",								
	BagSlotsNormalColour = "7CFC00",								
	BagSlotsBA = 0,

	-- BANK SLOTS
	ShowBankSlots = false,
	LockBankSlots = false,
	BankSlotsFormat = "Used/Total",
	BankSlotsIconW = 32,
	BankSlotsIconH = 32,
	BankSlotsIconX = 0,
	BankSlotsIconY = 0,
	BankSlotsFont = "Open Sans - Bold",
	BankSlotsFontSize = 16,
	BankSlotsFontStyle = "Soft Shadow - Thin",
	BankSlotsX = 200,
	BankSlotsY = 100,
	BankSlotsDefaultColour = "FFFFFF",								
	BankSlotsAlertColour = "FF3030",								
	BankSlotsWarningColour = "FFB90F",								
	BankSlotsNormalColour = "7CFC00",								
	BankSlotsBA = 0,

	-- THIEVERY 
	ShowThievery = false,
	LockThievery = false,
	ThieveryFormat = "SI (TV) » US/TS - UF/TF",
	ThieveryIconW = 32,
	ThieveryIconH = 32,
	ThieveryIconX = 0,
	ThieveryIconY = 0,
	ThieveryFont = "Open Sans - Bold",
	ThieveryFontSize = 16,
	ThieveryFontStyle = "Soft Shadow - Thin",
	ThieveryX = 200,
	ThieveryY = 100,
	ThieveryDefaultColour = "FFFFFF",								
	ThieveryAlertColour = "FF3030",								
	ThieveryWarningColour = "FFB90F",
	ThieveryGoldColour = "FFB90F",									
	ThieveryNormalColour = "7CFC00",
	ThieveryBA = 0,

	-- BOUNTY
	ShowBounty = false,
	LockBounty = false,
	BountyFormat = "Status (Bounty)/BT (HE)",
	BountyIconW = 32,
	BountyIconH = 32,
	BountyIconX = 0,
	BountyIconY = 0,
	BountyFont = "Open Sans - Bold",
	BountyFontSize = 16,
	BountyFontStyle = "Soft Shadow - Thin",
	BountyX = 200,
	BountyY = 100,
	BountyDefaultColour = "FFFFFF",								
	BountyAlertColour = "FF3030",								
	BountyWarningColour = "FFB90F",	
	BountyGoldColour = "FFB90F",							
	BountyNormalColour = "7CFC00",								
	BountyBA = 0,	

	-- RIDING
	ShowRiding = false,
	ShowDetailedRiding = false,
	LockRiding = false,
	RidingIconW = 32,
	RidingIconH = 32,
	RidingIconX = 0,
	RidingIconY = 0,
	RidingFont = "Open Sans - Bold",
	RidingFontSize = 16,
	RidingFontStyle = "Soft Shadow - Thin",
	RidingX = 500,
	RidingY = 100,
	RidingDefaultColour = "FFFFFF",									
	RidingAlertColour = "FF3030",									
	RidingWarningColour = "FFB90F",									
	RidingNormalColour = "7CFC00",									
	RidingBA = 0,
	SWWM = false,

	-- BLACKSMITHING
	ShowBlacksmithing = false,
	LockBlacksmithing = false,
	BlacksmithingIconW = 32,
	BlacksmithingIconH = 32,
	BlacksmithingIconX = 0,
	BlacksmithingIconY = 0,
	BlacksmithingFont = "Open Sans - Bold",
	BlacksmithingFontSize = 16,
	BlacksmithingFontStyle = "Soft Shadow - Thin",
	BlacksmithingX = 750,
	BlacksmithingY = 100,
	BlacksmithingDefaultColour = "FFFFFF",							
	BlacksmithingAlertColour = "FF3030",							
	BlacksmithingWarningColour = "FFB90F",							
	BlacksmithingNormalColour = "7CFC00",							
	BlacksmithingBA = 0,

	-- WOODWORKING
	ShowWoodworking = false,
	LockWoodworking = false,
	WoodworkingIconW = 32,
	WoodworkingIconH = 32,
	WoodworkingIconX = 0,
	WoodworkingIconY = 0,
	WoodworkingFont = "Open Sans - Bold",
	WoodworkingFontSize = 16,
	WoodworkingFontStyle = "Soft Shadow - Thin",
	WoodworkingX = 1000,
	WoodworkingY = 100,
	WoodworkingDefaultColour = "FFFFFF",							
	WoodworkingAlertColour = "FF3030",								
	WoodworkingWarningColour = "FFB90F",							
	WoodworkingNormalColour = "7CFC00",								
	WoodworkingBA = 0,

	-- CLOTHING
	ShowClothing = false,
	LockClothing = false,
	ClothingIconW = 32,
	ClothingIconH = 32,
	ClothingIconX = 0,
	ClothingIconY = 0,
	ClothingFont = "Open Sans - Bold",
	ClothingFontSize = 16,
	ClothingFontStyle = "Soft Shadow - Thin",
	ClothingX = 1250,
	ClothingY = 100,
	ClothingDefaultColour = "FFFFFF",								
	ClothingAlertColour = "FF3030",									
	ClothingWarningColour = "FFB90F",								
	ClothingNormalColour = "7CFC00",								
	ClothingBA = 0,

	-- SOUL GEMS
	ShowSoulGems = false,
	LockSoulGems = false,
	SoulGemsFormat = "Filled/Total",
	SoulGemsIconW = 32,
	SoulGemsIconH = 32,
	SoulGemsIconX = 0,
	SoulGemsIconY = 0,
	SoulGemsFont = "Open Sans - Bold",
	SoulGemsFontSize = 16,
	SoulGemsFontStyle = "Soft Shadow - Thin",
	SoulGemsX = 350,
	SoulGemsY = 100,
	SoulGemsDefaultColour = "FFFFFF",								
	SoulGemsAlertColour = "FF3030",									
	SoulGemsWarningColour = "FFB90F",								
	SoulGemsNormalColour = "7CFC00",								
	SoulGemsBA = 0,

	-- WEAPON CHARGE
	ShowWeaponCharge = false,	
	LockWeaponCharge = false,
	WeaponChargeIconW = 32,
	WeaponChargeIconH = 32,
	WeaponChargeIconX = 0,
	WeaponChargeIconY = 0,
	WeaponChargeFont = "Open Sans - Bold",
	WeaponChargeFontSize = 16,
	WeaponChargeFontStyle = "Soft Shadow - Thin",
	WeaponChargeX = 1500,
	WeaponChargeY = 100,
	WeaponChargeDefaultColour = "FFFFFF",							
	WeaponChargeAlertColour = "FF3030",								
	WeaponChargeWarningColour = "FFB90F",							
	WeaponChargeNormalColour = "7CFC00",							
	WeaponChargeFormat = "% Only",
	WeaponChargeBA = 0,
	AutoChargeWeaponEnabled = false,
	AutoChargeWeaponThreshold = 10,

	-- ATTRIBUTE POINTS	
	ShowAttributePoints = false,
	LockAttributePoints = false,
	AttributePointsFormat = "Spent/Total",
	AttributePointsIconW = 32,
	AttributePointsIconH = 32,
	AttributePointsIconX = 0,
	AttributePointsIconY = 0,
	AttributePointsFont = "Open Sans - Bold",
	AttributePointsFontSize = 16,
	AttributePointsFontStyle = "Soft Shadow - Thin",
	AttributePointsX = 1800,
	AttributePointsY = 100,
	AttributePointsDefaultColour = "FFFFFF",						
	AttributePointsAlertColour = "FF3030",							
	AttributePointsWarningColour = "FFB90F",						
	AttributePointsNormalColour = "7CFC00",							
	AttributePointsBA = 0,

	-- SKYSHARDS	
	ShowSkyShards = false,
	LockSkyShards = false,
	SkyShardsIconW = 32,
	SkyShardsIconH = 32,
	SkyShardsIconX = 0,
	SkyShardsIconY = 0,
	SkyShardsFont = "Open Sans - Bold",
	SkyShardsFontSize = 16,
	SkyShardsFontStyle = "Soft Shadow - Thin",
	SkyShardsX = 50,
	SkyShardsY = 150,
	SkyShardsDefaultColour = "FFFFFF",								
	SkyShardsAlertColour = "FF3030",								
	SkyShardsWarningColour = "FFB90F",								
	SkyShardsNormalColour = "7CFC00",								
	SkyShardsBA = 0,

	-- SKILL POINTS	
	ShowSkillPoints = false,
	LockSkillPoints = false,
	SkillPointsFormat = "Spent/Total",
	SkillPointsIconW = 32,
	SkillPointsIconH = 32,
	SkillPointsIconX = 0,
	SkillPointsIconY = 0,
	SkillPointsFont = "Open Sans - Bold",
	SkillPointsFontSize = 16,
	SkillPointsFontStyle = "Soft Shadow - Thin",
	SkillPointsX = 150,
	SkillPointsY = 150,
	SkillPointsDefaultColour = "FFFFFF",							
	SkillPointsAlertColour = "FF3030",								
	SkillPointsWarningColour = "FFB90F",							
	SkillPointsNormalColour = "7CFC00",								
	SkillPointsBA = 0,

	-- CHAMPION XP
	ShowChampionXP = false,
	LockChampionXP = false,
	ChampionXPIconW = 32,
	ChampionXPIconH = 32,
	ChampionXPIconX = 0,
	ChampionXPIconY = 0,
	ChampionXPFont = "Open Sans - Bold",
	ChampionXPFontSize = 16,
	ChampionXPFontStyle = "Soft Shadow - Thin",
	ChampionXPX = 750,
	ChampionXPY = 200,
	ChampionXPDefaultColour = "FFFFFF",									
	ChampionXPESColour = "FF3030",											
	ChampionXPMSColour = "FFB90F",											
	ChampionXPLSColour = "7CFC00",
	ChampionXPENColour = "1E90FF",												
	ChampionXPFormat = "CP » Current/Max (%) » Sign",
	ChampionXPBA = 0,

	-- ALLIANCE POINTS	
	ShowAlliancePoints = false,
	LockAlliancePoints = false,
	AlliancePointsIconW = 32,
	AlliancePointsIconH = 32,
	AlliancePointsIconX = 0,
	AlliancePointsIconY = 0,
	AlliancePointsFont = "Open Sans - Bold",
	AlliancePointsFontSize = 16,
	AlliancePointsFontStyle = "Soft Shadow - Thin",
	AlliancePointsX = 350,
	AlliancePointsY = 150,
	AlliancePointsDefaultColour = "7CFC00",							
	AlliancePointsAlertColour = "FF3030",							
	AlliancePointsWarningColour = "FFB90F",							
	AlliancePointsNormalColour = "7CFC00",							
	AlliancePointsBA = 0,

	-- AVA PROGRESS
	ShowAvARank = false,
	LockAvARank = false,
	AvARankDetailed = false,
	AvAAutoShow = false,
	AvARankIconW = 32,
	AvARankIconH = 32,
	AvARankIconX = 0,
	AvARankIconY = 0,
	AvARankFont = "Open Sans - Bold",
	AvARankFontSize = 16,
	AvARankFontStyle = "Soft Shadow - Thin",
	AvARankX = 800,
	AvARankY = 250,
	AvARankDefaultColour = "FFFFFF",
	AvARankColour = "1E90FF",
	AvARankAPColour = "7CFC00", 									
	AvARankESColour = "FF3030",											
	AvARankMSColour = "FFB90F",											
	AvARankLSColour = "7CFC00",											
	AvARankFormat = "Rank » Current/Max (%)",
	AvARankBA = 0,

	-- ACHIEVEMENT POINTS	
	ShowAchievementPoints = false,
	LockAchievementPoints = false,
	AchievementPointsIconW = 32,
	AchievementPointsIconH = 32,
	AchievementPointsIconX = 0,
	AchievementPointsIconY = 0,
	AchievementPointsFont = "Open Sans - Bold",
	AchievementPointsFontSize = 16,
	AchievementPointsFontStyle = "Soft Shadow - Thin",
	AchievementPointsX = 500,
	AchievementPointsY = 150,
	AchievementPointsDefaultColour = "FFFFFF",						
	AchievementPointsAlertColour = "FF3030",						
	AchievementPointsWarningColour = "FFB90F",						
	AchievementPointsNormalColour = "7CFC00",						
	AchievementPointsFormat = "Current/Max (%)",
	AchievementPointsBA = 0,

	-- FRIENDS	
	ShowFriends = false,
	LockFriends = false,
	FriendsFormat = "Online/Total",
	FriendsIconW = 32,
	FriendsIconH = 32,
	FriendsIconX = 0,
	FriendsIconY = 0,
	FriendsFont = "Open Sans - Bold",
	FriendsFontSize = 16,
	FriendsFontStyle = "Soft Shadow - Thin",
	FriendsX = 800,
	FriendsY = 150,
	FriendsDefaultColour = "FFFFFF",								
	FriendsAlertColour = "FF3030",									
	FriendsWarningColour = "FFB90F",								
	FriendsNormalColour = "7CFC00",									
	FriendsBA = 0,

	-- PLAYER INFO	
	ShowTimePlayed = false,
	ShowDetailedTimePlayed = false,
	LockTimePlayed = false,
	TimePlayedIconW = 32,
	TimePlayedIconH = 32,
	TimePlayedIconX = 0,
	TimePlayedIconY = 0,
	TimePlayedFont = "Open Sans - Bold",
	TimePlayedFontSize = 16,
	TimePlayedFontStyle = "Soft Shadow - Thin",
	TimePlayedX = 950,
	TimePlayedY = 150,
	TimePlayedDefaultColour = "FFFFFF",								
	TimePlayedAlertColour = "FF3030",								
	TimePlayedWarningColour = "FFB90F",								
	TimePlayedNormalColour = "7CFC00",								
	TimePlayedBA = 0,
	
	-- COMBAT STATE	
	ShowCombatState = false,
	LockCombatState = false,
	CombatStateIconW = 32,
	CombatStateIconH = 32,
	CombatStateIconX = 0,
	CombatStateIconY = 0,
	CombatStateFont = "Open Sans - Bold",
	CombatStateFontSize = 16,
	CombatStateFontStyle = "Soft Shadow - Thin",
	CombatStateX = 1400,
	CombatStateY = 150,
	CombatStateDefaultColour = "FFFFFF",							
	CombatStateAlertColour = "FF3030",								
	CombatStateWarningColour = "FFB90F",							
	CombatStateNormalColour = "7CFC00",								
	CombatStateBA = 0,
	AutoSheatWeapon = false,
	SheatTimer = 3000,
	SCCByCombat = false,
	SCCInCombatColour = "FF3030",

	-- VAMPIRISM	
	ShowVampirism = false,
	LockVampirism = false,
	VampirismIconW = 32,
	VampirismIconH = 32,
	VampirismIconX = 0,
	VampirismIconY = 0,
	VampirismFont = "Open Sans - Bold",
	VampirismFontSize = 16,
	VampirismFontStyle = "Soft Shadow - Thin",
	VampirismX = 1600,
	VampirismY = 150,
	VampirismDefaultColour = "FFFFFF",								
	VampirismAlertColour = "FF3030",								
	VampirismWarningColour = "FFB90F",								
	VampirismNormalColour = "7CFC00",								
	VampirismBA = 0,

	-- LYCANTHROPY	
	ShowLycanthropy = false,
	AutoShowLycanthropy = false,
	LockLycanthropy = false,
	LycanthropyIconW = 32,
	LycanthropyIconH = 32,
	LycanthropyIconX = 0,
	LycanthropyIconY = 0,
	LycanthropyFont = "Open Sans - Bold",
	LycanthropyFontSize = 16,
	LycanthropyFontStyle = "Soft Shadow - Thin",
	LycanthropyX = 1600,
	LycanthropyY = 275,
	LycanthropyDefaultColour = "FFFFFF",								
	LycanthropyAlertColour = "FF3030",								
	LycanthropyWarningColour = "FFB90F",								
	LycanthropyNormalColour = "7CFC00",								
	LycanthropyBA = 0,

	-- CRAFTING XP	
	ShowCraftingXP = false,
	AutoShowCraftingXP = false,
	LockCraftingXP = false,
	CraftingXPIconW = 32,
	CraftingXPIconH = 32,
	CraftingXPIconX = 0,
	CraftingXPIconY = 0,
	CraftingXPFont = "Open Sans - Bold",
	CraftingXPFontSize = 16,
	CraftingXPFontStyle = "Soft Shadow - Thin",
	CraftingXPX = 50,
	CraftingXPY = 200,
	CraftingXPDefaultColour = "FFFFFF",								
	CraftingXPValueColour = "1E90FF",
	CraftingXPBA = 0,

	-- NOTIFICATION	
	ShowNotification = false,
	IgnoreMSGSecond = 30,
	LockNotification = false,
	NotificationIconW = 32,
	NotificationIconH = 32,
	NotificationIconX = 0,
	NotificationIconY = 0,
	NotificationFont = "Open Sans - Bold",
	NotificationFontSize = 16,
	NotificationFontStyle = "Soft Shadow - Thin",
	NotificationX = 200,
	NotificationY = 200,
	NotificationDefaultColour = "FFFFFF",									
	NotificationAlertColour = "FF3030",										
	NotificationWarningColour = "FFB90F",								
	NotificationBA = 0,
	NotificationWhisper = false,
	NotificationRecharge = false,
	NotificationDurability = false,	

	-- SUBTITLES
	ShowSubtitles = false,
	LockSubtitles = false,
	SubtitlesIconW = 32,
	SubtitlesIconH = 32,
	SubtitlesIconX = 0,
	SubtitlesIconY = 0,
	SubtitlesFont = "Open Sans - Bold",
	SubtitlesFontSize = 16,
	SubtitlesFontStyle = "Soft Shadow - Thin",
	SubtitlesX = 0,
	SubtitlesY = 0,
	SubtitlesDefaultColour = "FFFFFF",								
	SubtitlesNNameColour = "C5C29E",								
	ShowNPCName = true,
	SubtitlesFadeTime = 20000,
	SubtitlesFormat = "Brackets",
	SubtitlesAlignment = false,
	SubtitlesFirstTime = true,

	-- RETICLE	
	ShowTargetInfo = false,

	ReticleIgnoreCritter = false,
	ReticleFormat = "Semi-Extended",
	ReticleHealthFormat = "[Current] [%]",

	ReticleFont = "Open Sans - Bold",
	ReticleFontSize = 16,
	ReticleFontStyle = "Soft Shadow - Thin",

	ReticleX = 0,
	ReticleY = 0,

	ChangeReticleTexture = false,
	ReticleTexture = "Cross",
	ReticleTextureScale = 0.5,	
	
	ReticleReactionColouring = false,	
	ReticleUseRCforRT = false,

	ReticlePartialColouring = false,
	ReticleUsePCforRT = false,

	ReticleLVRMode = "Difficulty Mode",
	ReticleNameMode = "Reaction Mode",
	ReticleHealthMode = "Reaction Mode",
	ReticleGenderMode = "Split Gender Mode",
	ReticleRaceMode = "Ext. Alliance Mode",
	ReticleClassMode = "Reaction Mode",
	ReticleTiCaMode = "Alliance Mode",
	ReticleAvAMode = "Difficulty Mode",
	ReticleAllianceMode = "Alliance Mode",

	ReticleRCNoTarget = "FFFFFF",
	ReticleRCDead = "EAEAEA",
	ReticleRCUnidentified = "C5C29E",
	ReticleRCHostile = "FF3030",
	ReticleRCNeutral = "FFB90F",
	ReticleRCFriendly = "7CFC00",
	ReticleRCPlayerAlly = "1E90FF",
	ReticleRCNPCAlly = "7CFC00",
	ReticleRCMate = "FFFFFF",
	ReticleRCGuildy = "FFFFFF",
	
	ReticleLowLVR = "7CFC00",
	ReticleNormalLVR = "FFB90F",
	ReticleHighLVR = "FF3030",

	ReticleFemale = "FFB90F",
	ReticleMale = "1E90FF",

	ReticleDC = "1E90FF",
	ReticleAD = "FFB90F",
	ReticleEP = "FF3030",
	ReticleIMP = "CD2626",
	ReticleNoAlliance = "FFFFFF",

	ReticleTextureColour = "FFFFFF",
	ReticleDefaultColour = "FFFFFF",								
	ReticleNameColour = "FFFFFF",									
	ReticleLVRColour = "FFFFFF",									
	ReticleCHealthColour = "FFFFFF",								
	ReticleMHealthColour = "FFFFFF",								
	ReticleHPercColour = "FFFFFF",									
	ReticleGenderColour = "FFFFFF",									
	ReticleRaceColour = "FFFFFF",									
	ReticleClassColour = "FFFFFF",									
	ReticleTiCaColour = "FFFFFF",									
	ReticleAvAColour = "FFFFFF",									
	ReticleAllianceColour = "FFFFFF",

	ReticleFirstTime = true,

	-- CHAMBERLAIN
	EnableChamberlain = false,
	ChamberlainFormat = "Extended",
	ChamberlainUseAHRules = false,
	ChamberlainDefaultColour = "FFFFFF",								
	ChamberlainAlertColour = "FF3030",								
	ChamberlainWarningColour = "FFB90F",								
	ChamberlainNormalColour = "7CFC00",
	ChamberlainDailyColour = "1E90FF",
	ChamberlainX = 37,
	ChamberlainY = 162,
	ChamberlainW = 650,
	ChamberlainH = 468,
	ChamberlainBA = 0.50,
	ChamberlainIEH = 375,
	ChamberlainFont = "Open Sans - Bold",
	ChamberlainFontStyle = "Soft Shadow - Thin",
	ChamberlainFontSize = 15,
	ChamberlainLedger =	{},
}