ShowTraitOnListLang = {
    ["en"] = {
        ICON_SIZE = "Icon Size",
        ICON_POSTION_TOP = "icon Postion top",
        ICON_POSTION_LEFT = "icon Postion left",
        ICON_EQSIZE = "equipped Icon Size",
        ICON_EQPOSTION_TOP = "equipped icon Postion top",
        ICON_EQPOSTION_LEFT = "equipped icon Postion left",
    },
    ["fr"] = {
        ICON_SIZE = "Icon Size",
        ICON_POSTION_TOP = "icon Postion top",
        ICON_POSTION_LEFT = "icon Postion left",
        ICON_EQSIZE = "equipped Icon Size",
        ICON_EQPOSTION_TOP = "equipped icon Postion top",
        ICON_EQPOSTION_LEFT = "equipped icon Postion left",
    },
    ["de"] = {
        ICON_SIZE = "Icon Size",
        ICON_POSTION_TOP = "icon Postion top",
        ICON_POSTION_LEFT = "icon Postion left",
        ICON_EQSIZE = "equipped Icon Size",
        ICON_EQPOSTION_TOP = "equipped icon Postion top",
        ICON_EQPOSTION_LEFT = "equipped icon Postion left",
    },
    ["ru"] = {
        ICON_SIZE = "Icon Size",
        ICON_POSTION_TOP = "icon Postion top",
        ICON_POSTION_LEFT = "icon Postion left",
        ICON_EQSIZE = "equipped Icon Size",
        ICON_EQPOSTION_TOP = "equipped icon Postion top",
        ICON_EQPOSTION_LEFT = "equipped icon Postion left",
    },
    ["jp"] = {
        ICON_SIZE = "Icon Size",
        ICON_POSTION_TOP = "icon Postion top",
        ICON_POSTION_LEFT = "icon Postion left",
        ICON_EQSIZE = "equipped Icon Size",
        ICON_EQPOSTION_TOP = "equipped icon Postion top",
        ICON_EQPOSTION_LEFT = "equipped icon Postion left",
    },
    ["zh"] = {
        ICON_SIZE = "Icon Size",
        ICON_POSTION_TOP = "icon Postion top",
        ICON_POSTION_LEFT = "icon Postion left",
        ICON_EQSIZE = "equipped Icon Size",
        ICON_EQPOSTION_TOP = "equipped icon Postion top",
        ICON_EQPOSTION_LEFT = "equipped icon Postion left",
    },
}
