local Addon = LarvalTearMod
local M = Addon.Modules.SkillRespecConstants

M.SKILL_RESPEC_READY_RETRY_DELAYS_MS = { 0, 250, 500, 750, 1000 }
M.SKILL_RESPEC_START_RETRY_DELAY_MS = 2000
M.SKILL_RESPEC_MAX_START_ATTEMPTS = 5
M.SKILL_RESPEC_CONFIRM_RETRY_MS = 100
M.SKILL_RESPEC_CONFIRM_MAX_ATTEMPTS = 20

M.ROUTE_B_VERIFY_KICKOFF_DELAY_MS = 250
M.ROUTE_B_COMMIT_OBSERVE_POLL_MS = 250
M.ROUTE_B_COMMIT_OBSERVE_MAX_ATTEMPTS = 10
M.ROUTE_B_COMMIT_RETRY_DELAY_MS = 2000
M.ROUTE_B_COMMIT_MAX_RETRIES = 5
M.ROUTE_B_POST_COMMIT_VERIFY_INITIAL_DELAY_MS = 300
M.ROUTE_B_POST_COMMIT_VERIFY_RETRY_MS = 250
M.ROUTE_B_POST_COMMIT_VERIFY_MAX_ATTEMPTS = 10
M.ROUTE_B_MORPH_MAX_PASSES = 6
M.ROUTE_B_COMPLETION_POLL_MS = 250
M.ROUTE_B_COMPLETION_MAX_ATTEMPTS = 40
M.ROUTE_B_PASSIVE_EXACT_RETRY_DELAY_MS = 50
