-- Create namespace
DsRGuildPriceMenu = {}
local DsRGuildPriceMenu = DsRGuildPriceMenu  or {}

local LAM     = LibAddonMenu2

local DsRIcon = DsRglobals:HolidayIconLoad()

DsRGuildPriceMenu.name = "DsRGuildPriceMenu"

local MenuOptions,MenuPanel,MenuHandlers={},{},{}
local Settings={}

-------------------------------------------------------------------------------------------------------------------------------------------------
Settings = {
    [1]  = {name="DsRGuildMenue_accsettings",description=true},
    [2]  = {name="DsRGuildLoot_trade_support1",description=true},
    [3]  = {name="DsRGuildLoot_trade_support2",description=true},
    [4]  = {name="DsRGuildPrice_PriceOnOff",default=false,warning="ReloadUiWarn2",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.PriceOnOff end,
            setfnc=function(value) DsRGuildPrice.SavedVariables.PriceOnOff = value DsR.Menu.HandleReloadUIPressed() end,
            },
    [5]  = {name="DsRGuildPrice_FormatSettings",subheader=true},
    [6]  = {name="DsRGuildPrice_Thousandsep",dropdown=true,
            choices={"'", ",", ".", "_", PRICE_TOOLTIP_SPACE, PRICE_TOOLTIP_EMPTY},
            getfnc=function() return DsRGuildPrice.SavedVariables.Separator end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.Separator = newValue end,
            disable=function() return DsRGuildPrice.SavedVariables.PriceOnOff end,
            },
    [7]  = {name="DsRGuildPrice_RoundPrice",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.RoundPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.RoundPrice = newValue end,
            disable=function() return DsRGuildPrice.SavedVariables.PriceOnOff end,
            },
    [8]  = {name="DsRGuildPrice_ToolTipColor",colorpicker=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.TooltipColor.Red, DsRGuildPrice.SavedVariables.TooltipColor.Green, DsRGuildPrice.SavedVariables.TooltipColor.Blue end,
            setfnc=function(r, g, b) DsRGuildPrice.SavedVariables.TooltipColor.Red = r DsRGuildPrice.SavedVariables.TooltipColor.Green = g DsRGuildPrice.SavedVariables.TooltipColor.Blue = b end,
            disable=function() return DsRGuildPrice.SavedVariables.PriceOnOff end,
            },
    [9]  = {name="DsRGuildPrice_ToolTipInfoColor",colorpicker=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.TooltipPriceInfoColor.Red, DsRGuildPrice.SavedVariables.TooltipPriceInfoColor.Green, DsRGuildPrice.SavedVariables.TooltipPriceInfoColor.Blue end,
            setfnc=function(r, g, b) DsRGuildPrice.SavedVariables.TooltipPriceInfoColor.Red = r DsRGuildPrice.SavedVariables.TooltipPriceInfoColor.Green = g DsRGuildPrice.SavedVariables.TooltipPriceInfoColor.Blue = b end,
            disable=function() return DsRGuildPrice.SavedVariables.PriceOnOff end,
            },
    [10] = {name="DsRGuildPrice_TooltipLineSpacing",slider=true,maxvalue=10,minvalue=-10,step=1,
            getfnc=function() return DsRGuildPrice.SavedVariables.TooltipLineSpacing end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.TooltipLineSpacing = newValue end,
            disable=function() return DsRGuildPrice.SavedVariables.PriceOnOff end,
            },
    [11] = {name="DsRGuildPrice_SubMenueBoundItem",subheader=true},
    [12] = {name="DsRGuildPrice_BountVendorPrice",warning="ReloadUiWarn1",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.BoundItemsAsVendorPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.BoundItemsAsVendorPrice = newValue DsR.UI.ReloadUIButton() end,
            },
    [13] = {name="DsRGuildPrice_BountIndicator",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.MarkBoundItems end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.MarkBoundItems = newValue end,
            },
    [14] = {name="DsRGuildPrice_ToolTipInfoColor",colorpicker=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.BoundItemMarkColor.Red, DsRGuildPrice.SavedVariables.BoundItemMarkColor.Green, DsRGuildPrice.SavedVariables.BoundItemMarkColor.Blue end,
            setfnc=function(r, g, b) DsRGuildPrice.SavedVariables.BoundItemMarkColor.Red = r DsRGuildPrice.SavedVariables.BoundItemMarkColor.Green = g DsRGuildPrice.SavedVariables.BoundItemMarkColor.Blue = b end,
            },
    [15] = {name="DsRGuildPrice_SubMenueTooltipFont",subheader=true},
    [16]  = {name="DsRGuildPrice_TooltipFont",dropdown=true,
            choices={"ZoFontWinH5", "ZoFontWinH4", "ZoFontWinH3", "ZoFontWinH2", "ZoFontGameSmall", "ZoFontGame","ZoFontGameBold"},
            getfnc=function() return DsRGuildPrice.SavedVariables.Font end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.Font = newValue end,
            },
    [17]  = {name="DsRGuildPrice_TooltipinfoFont",dropdown=true,
            choices={"ZoFontWinH5", "ZoFontWinH4", "ZoFontWinH3", "ZoFontWinH2", "ZoFontGameSmall", "ZoFontGame","ZoFontGameBold"},
            getfnc=function() return DsRGuildPrice.SavedVariables.PriceInfoFont end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.PriceInfoFont = newValue end,
            },
    [18] = {name="DsRGuildPrice_SubMenueContextMenu",subheader=true},
    [19] = {name="DsRGuildPrice_ContextMenuUse",checkbox=true,
            getfnc=function() return  DsRGuildPrice.SavedVariables.UsePriceTooltipMenu end,
            setfnc=function(newValue)  DsRGuildPrice.SavedVariables.UsePriceTooltipMenu = newValue end,
            },
    [20] = {name="DsRGuildPrice_ContextMenuColor",colorpicker=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.ContextMenuColor.Red, DsRGuildPrice.SavedVariables.ContextMenuColor.Green, DsRGuildPrice.SavedVariables.ContextMenuColor.Blue end,
            setfnc=function(r, g, b) DsRGuildPrice.SavedVariables.ContextMenuColor.Red = r DsRGuildPrice.SavedVariables.ContextMenuColor.Green = g DsRGuildPrice.SavedVariables.ContextMenuColor.Blue = b end,
            },
    [21] = {name="DsRGuildPrice_SubMenueLowPriceIndi",subheader=true},
    [22] = {name="DsRGuildPrice_LowPriceIndiTooltip",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.LowPriceIndicatorTooltip end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.LowPriceIndicatorTooltip = newValue end,
            },
    [23] = {name="DsRGuildPrice_LowPriceIndiGrid",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.LowPriceIndicatorGrid end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.LowPriceIndicatorGrid = newValue end,
            },
    [24] = {name="DsRGuildPrice_LowPriceIndiColor",colorpicker=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.VendorPriceLowPriceIndicatorColor.Red, DsRGuildPrice.SavedVariables.VendorPriceLowPriceIndicatorColor.Green, DsRGuildPrice.SavedVariables.VendorPriceLowPriceIndicatorColor.Blue end,
            setfnc=function(r, g, b) DsRGuildPrice.SavedVariables.VendorPriceLowPriceIndicatorColor.Red = r DsRGuildPrice.SavedVariables.VendorPriceLowPriceIndicatorColor.Green = g DsRGuildPrice.SavedVariables.VendorPriceLowPriceIndicatorColor.Blue = b end,
            },
    [25] = {name="DsRGuildPrice_SubMenueOverridePrice",subheader=true},
    [26] = {name="DsRGuildPrice_OverridePriceGrid",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.UseGridItemPriceOverride end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.UseGridItemPriceOverride = newValue end,
            },
    [27]  = {name="DsRGuildPrice_OverridePriceGridBeh",dropdown=true,
            choices={PRICE_TOOLTIP_DEFAULT_PRICE, PRICE_TOOLTIP_AVERAGE_PRICE, PRICE_TOOLTIP_MM_PRICE, PRICE_TOOLTIP_TTC_PRICE, PRICE_TOOLTIP_ATT_PRICE, PRICE_TOOLTIP_BEST_PRICE},
            getfnc=function() return DsRGuildPrice.SavedVariables.GridItemPriceOverrideBehaviour end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.GridItemPriceOverrideBehaviour = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseGridItemPriceOverride) end,
            },
    [28] = {name="DsRGuildPrice_OverridePriceFirstOn",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.EnableFirstPriceInGrid end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.EnableFirstPriceInGrid = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseGridItemPriceOverride) end,
            },
    [29] = {name="DsRGuildPrice_OverridePriceSecondOn",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.EnableSecondPriceInGrid end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.EnableSecondPriceInGrid = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseGridItemPriceOverride) end,
            },
    [30] = {name="DsRGuildPrice_OverridePriceSwitch",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.ShowSingleItemPriceInGrid end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.ShowSingleItemPriceInGrid = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseGridItemPriceOverride) end,
            },
    [31] = {name="DsRGuildPrice_SubMenuePriceSettings",subheader=true},
    [32] = {name="DsRGuildPrice_PriceSettingsVendor",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.DisplayVendorPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.DisplayVendorPrice = newValue end,
            },
    [33] = {name="DsRGuildPrice_PriceSettingsRound",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.RoundPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.RoundPrice = newValue end,
            },
    [34] = {name="DsRGuildPrice_SubMenueTTCsettings",attention=true},
    [35] = {name="DsRGuildPrice_TTCuse",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.UseTTCPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.UseTTCPrice = newValue end,
            },
    [36] = {name="DsRGuildPrice_TTCscale",slider=true,maxvalue=50,minvalue=-50,step=1,
            getfnc=function() return DsRGuildPrice.SavedVariables.ScaleTTCPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.ScaleTTCPrice = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseTTCPrice) end,
            },
    [37] = {name="DsRGuildPrice_TTCalternatscale",slider=true,maxvalue=50,minvalue=-50,step=1,
            getfnc=function() return DsRGuildPrice.SavedVariables.ScaleAvgTTCPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.ScaleAvgTTCPrice = newValue end,
            disable=function() return not (DsRGuildPrice.SavedVariables.UseTTCPrice and DsRGuildPrice.SavedVariables.IncludeAvgTTCPrice) end
            },
    [38] = {name="DsRGuildPrice_TTCalternat",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.IncludeAvgTTCPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.IncludeAvgTTCPrice = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseTTCPrice) end,
            },
    [39] = {name="DsRGuildPrice_TTCalternatColor",colorpicker=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.AvgTTCPriceColor.Red, DsRGuildPrice.SavedVariables.AvgTTCPriceColor.Green, DsRGuildPrice.SavedVariables.AvgTTCPriceColor.Blue end,
            setfnc=function(r, g, b) DsRGuildPrice.SavedVariables.AvgTTCPriceColor.Red = r DsRGuildPrice.SavedVariables.AvgTTCPriceColor.Green = g DsRGuildPrice.SavedVariables.AvgTTCPriceColor.Blue = b end,
            disable=function() return not (DsRGuildPrice.SavedVariables.UseTTCPrice and DsRGuildPrice.SavedVariables.IncludeAvgTTCPrice) end,
            },
    [40] = {name="DsRGuildPrice_TTCtooltip",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.DisplayTTCPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.DisplayTTCPrice = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseTTCPrice) end,
            },
    [41] = {name="DsRGuildPrice_TTCtooltipOri",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.DisplayTTCPriceInfo end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.DisplayTTCPriceInfo = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseTTCPrice) end,
            },
    [42] = {name="DsRGuildPrice_SubMenueMMsettings",attention=true},
    [43] = {name="DsRGuildPrice_MMuse",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.UseMMPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.UseMMPrice = newValue end,
            },
    [44] = {name="DsRGuildPrice_MMscale",slider=true,maxvalue=50,minvalue=-50,step=1,
            getfnc=function() return DsRGuildPrice.SavedVariables.ScaleMMPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.ScaleMMPrice = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseMMPrice) end,
            },
    [45] = {name="DsRGuildPrice_MMtooltip",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.DisplayMMPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.DisplayMMPrice = newValue end,
            disabled=function() return (not DsRGuildPrice.SavedVariables.UseMMPrice) end,
            },
    [46] = {name="DsRGuildPrice_MMtooltipOri",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.DisplayMMPriceInfo end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.DisplayMMPriceInfo = newValue end,
            disabled=function() return (not DsRGuildPrice.SavedVariables.UseMMPrice) end,
            },
    [47] = {name="DsRGuildPrice_SubMenueATTsettings",attention=true},
    [48] = {name="DsRGuildPrice_ATTuse",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.UseATTPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.UseATTPrice = newValue end,
            },
    [49] = {name="DsRGuildPrice_ATTscale",slider=true,maxvalue=50,minvalue=-50,step=1,
            getfnc=function() return DsRGuildPrice.SavedVariables.ScaleATTPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.ScaleATTPrice = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseATTPrice) end,
            },
    [50] = {name="DsRGuildPrice_ATTdayrange",slider=true,maxvalue=30,minvalue=1,step=1,
            getfnc=function() return DsRGuildPrice.SavedVariables.ATTDays end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.ATTDays = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseATTPrice) end,
            },
    [51] = {name="DsRGuildPrice_ATTtooltip",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.DisplayATTPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.DisplayATTPrice = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseATTPrice) end,
            },
    [52] = {name="DsRGuildPrice_ATTtooltipOri",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.DisplayATTPriceInfo end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.DisplayATTPriceInfo = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseATTPrice) end,
            },
    [53] = {name="DsRGuildPrice_SubMenueAvgPrice",attention=true},
    [54] = {name="DsRGuildPrice_AvgPriceuse",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.UseAveragePrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.UseAveragePrice = newValue end,
            },
    [55] = {name="DsRGuildPrice_AvgPricedisplay",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.DisplayAveragePrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.DisplayAveragePrice = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseAveragePrice) end,
            },
    [56] = {name="DsRGuildPrice_AvgPriceIncTTC",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.IncludeTTCInAP end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.IncludeTTCInAP = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseAveragePrice) end,
            },
    [57] = {name="DsRGuildPrice_AvgPriceIncTTCalt",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.IncludeTTCAvgInAP end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.IncludeTTCAvgInAP = newValue end,
            disable=function() return not (DsRGuildPrice.SavedVariables.UseAveragePrice and DsRGuildPrice.SavedVariables.IncludeTTCInAP) end,
            },
    [58] = {name="DsRGuildPrice_AvgPriceIncMM",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.IncludeMMInAP end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.IncludeMMInAP = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseAveragePrice) end,
            },
    [59] = {name="DsRGuildPrice_AvgPriceIncATT",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.IncludeATTInAP end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.IncludeATTInAP = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseAveragePrice) end,
            },
    [60] = {name="DsRGuildPrice_SubMenueBestPrice",attention=true},
    [61] = {name="DsRGuildPrice_BestPriceuse",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.UseBestPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.UseBestPrice = newValue end,
            },
    [62] = {name="DsRGuildPrice_BestPricedisplay",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.DisplayBestPrice end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.DisplayBestPrice = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseBestPrice) end,
            },
    [63] = {name="DsRGuildPrice_BestPriceTTCalt",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.IncludeTTCAvgInBP end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.IncludeTTCAvgInBP = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseBestPrice) end,
            },
    [64] = {name="DsRGuildPrice_BestPriceprofit",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.IncludePPInBP end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.IncludePPInBP = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseBestPrice) end,
            },
    [65] = {name="DsRGuildPrice_BestPricesource",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.DisplaySourceInBP end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.DisplaySourceInBP = newValue end,
            disable=function() return (not DsRGuildPrice.SavedVariables.UseBestPrice) end,
            },
    [66] = {name="DsRGuildPrice_SubMenueDoubleTooltip",subheader=true},
    [67]  = {name="DsRGuildPrice_DoubleFix",checkbox=true,
            getfnc=function() return DsRGuildPrice.SavedVariables.FixDoubleTooltip end,
            setfnc=function(newValue) DsRGuildPrice.SavedVariables.FixDoubleTooltip = newValue end,
            },
}

-------------------------------------------------------------------------------------------------------------------------------------------------
function DsRGuildPriceMenu:SetupMenueSettings()

-- MENU NEW
    local DsRMenu=DsR and DsR.InternalMenu
    local Panel={
        type        ="panel",
        name        =(DsRMenu and "|c9fb6cd10.|r |t28:28:/DsRGuildHall/misc/tradehammer.dds|t" or "")..DsR.Localization[DsR.language].IndexTradingPrice,
        displayName =(DsRMenu and "|c9fb6cd10.|r |t28:28:/DsRGuildHall/misc/tradehammer.dds|t" or "")..DsR.Localization[DsR.language].IndexTradingPrice,
        author      ="|cD8F781Has|r|cF3F781enw|r|cF5DA81arr|r|cF7BE81ior|r",
    }
    local MenuOptions={}
    local index=0
    for i,data in pairs(Settings) do
        index=index+1
        local _name    = data.name
        local _tip     = DsR.Localization[DsR.language][data.name.."Desc"] or nil

        if data.header then
                MenuOptions[index]=
                {	type     = "header",
                    name     = _name,
                    disabled = data.disable
                }
        elseif data.subheader then
                MenuOptions[index]=
                {	type = "subheader",
                    name = _name,
                }
        elseif data.description then
                MenuOptions[index]=
                {	type = "description",
                    name = _name,
                }
        elseif data.attention then
                MenuOptions[index]=
                {	type = "attention",
                    name = _name,
                }
        elseif data.slider then
            MenuOptions[index]=
            {	type		= "slider",
                name		= _name,
                tooltip	    = _tip,
                min		    = data.minvalue,
                max		    = data.maxvalue,
                step		= data.step,
                getFunc	    = data.getfnc,
                setFunc	    = data.setfnc,
                default	    = data.default,
                disabled    = data.disable,
                warning     = data.warning,
            }
        elseif data.dropdown then
            MenuOptions[index]=
            {	type	    = "dropdown",
                name	    = _name,
                tooltip	    = _tip,
                choices	    = data.choices,
                getFunc	    = data.getfnc,
                setFunc	    = data.setfnc,
                default	    = data.default,
                disabled    = data.disable,
                warning     = data.warning,
            }
        elseif data.button then
            MenuOptions[index]=
            {	type	    = "button",
                name	    = _name,
                tooltip	    = _tip,
                func	    = data.func,
                warning     = data.warning,
            }
        elseif data.checkbox then
            MenuOptions[index]=
            {	type		= "checkbox",
                name		= _name,
                tooltip	    = _tip,
                getFunc	    = data.getfnc,
                setFunc	    = data.setfnc,
                default	    = data.default,
                disabled    = data.disable,
                warning     = data.warning,
            }
        elseif data.editbox then
            MenuOptions[index]=
            {	type		= "editbox",
                name		= _name,
                tooltip	    = _tip,
                getFunc	    = data.getfnc,
                setFunc	    = data.setfnc,
                default	    = data.default,
                disabled    = data.disable,
                warning     = data.warning,
            }
        elseif data.colorpicker then
            MenuOptions[index]=
            {	type	    = "colorpicker",
                name	    = _name,
                tooltip	    = _tip,
                getFunc	    = data.getfnc,
                setFunc	    = data.setfnc,
                default	    = data.default,
                disabled    = data.disable,
                warning     = data.warning,
            }
        end
    end
    DsR.Menu.RegisterPanel("DsRPricePanel_Menu_1",Panel)
    DsR.Menu.RegisterOptions("DsRPricePanel_Menu_1", MenuOptions) 
end
