local TTMP = _G.TamrielTomesMapPins
local ICONS = TTMP.icons

TTMP:RegisterChallengeData({
    {
        key = "knight_commander_panthius",
        label = "Knight Commander Panthius",
        icon = ICONS.worldBoss,
        activityIds = { 663 },
        match = {
            "knight commander panthis",
            "knight commander panthius",
            "panthis",
            "panthius",
        },
        pins = {
            { type = "poi", zoneId = 823, poiIndex = 21, label = "Knight Commander Panthius" },
        },
    },
    {
        key = "bogdan_lord_warden",
        label = "Bogdan the Nightflame / Lord Warden Dusk",
        icon = ICONS.groupDungeon,
        activityIds = { 668 },
        match = {
            "bogdan the nightflame",
            "lord warden dusk",
            "elden hollow 2",
            "elden hollow ii",
            "imperial city prison",
        },
        pins = {
            { type = "poi", zoneId = 383, poiIndex = 58, label = "Bogdan the Nightflame" },
            { type = "poi", zoneId = 181, poiIndex = 104, label = "Lord Warden Dusk" },
        },
    },
    {
        key = "lava_queen_molag_kena",
        label = "Symphony of Blades / Lava Queen / Molag Kena",
        icon = ICONS.groupDungeon,
        activityIds = { 669 },
        match = {
            "symphony of blades",
            "depths of malatar",
            "lava queen",
            "molag kena",
            "blessed crucible",
            "white-gold tower",
            "white gold tower",
        },
        pins = {
            { type = "poi", zoneId = 823, poiIndex = 17, label = "Symphony of Blades" },
            { type = "poi", zoneId = 103, poiIndex = 42, label = "Lava Queen" },
            { type = "poi", zoneId = 181, poiIndex = 105, label = "Molag Kena" },
            { type = "poi", zoneId = 643, poiIndex = 50, label = "Molag Kena" },
            { type = "poi", zoneId = 643, poiIndex = 51, label = "Molag Kena" },
            { type = "poi", zoneId = 643, poiIndex = 52, label = "Molag Kena" },
        },
    },
    {
        key = "serpent_sanctum_ophidia",
        label = "The Serpent",
        icon = ICONS.trial,
        activityIds = { 670 },
        match = {
            "defeat the serpent",
            "sanctum ophidia",
        },
        pins = {
            { type = "poi", zoneId = 888, poiIndex = 33, label = "The Serpent" },
        },
    },
    {
        key = "wrothgar_public_dungeon_group_event",
        label = "Wrothgar Public Dungeon Group Event",
        icon = ICONS.publicDungeon,
        activityIds = { 666 },
        match = {
            "public dungeon group event in wrothgar",
            "group event in wrothgar",
            "old orsinium",
            "rkindaleft",
        },
        pins = {
            { type = "poi", zoneId = 684, poiIndex = 2, label = "Public Dungeon Group Event" },
            { type = "poi", zoneId = 684, poiIndex = 29, label = "Public Dungeon Group Event" },
        },
    },
    {
        key = "corintthac_zandadunoz",
        label = "Corintthac / Zandadunoz",
        icon = ICONS.worldBoss,
        activityIds = { 662 },
        match = {
            "corintthac the abomination",
            "zandadunoz the reborn",
            "corintthac",
            "zandadunoz",
        },
        pins = {
            { type = "poi", zoneId = 684, poiIndex = 15, label = "Corintthac the Abomination" },
            { type = "poi", zoneId = 684, poiIndex = 12, label = "Zandadunoz the Reborn" },
        },
    },
    {
        key = "qumehdi_zaman_macius_cento",
        label = "Qumehdi / Zaman / Macius Cento",
        activityIds = { 659 },
        match = {
            "qumehdi",
            "zaman",
            "macius cento",
            "village of the lost",
        },
        pins = {
            { type = "poi", zoneId = 92, poiIndex = 47, label = "Qumehdi / Zaman", icon = ICONS.worldBoss },
            { type = "poi", zoneId = 347, poiIndex = 40, label = "Macius Cento", icon = ICONS.publicDungeon },
        },
    },
    {
        key = "zymel_etitan_kruz",
        label = "Zymel Etitan / Zymel Kruz",
        icon = ICONS.worldBoss,
        activityIds = { 658 },
        match = {
            "zymel etitan",
            "zymel kruz",
        },
        pins = {
            { type = "poi", zoneId = 108, poiIndex = 41, label = "Zymel Etitan" },
            { type = "poi", zoneId = 19, poiIndex = 49, label = "Zymel Kruz" },
        },
    },
    {
        key = "complete_arena",
        label = "Complete 1 Arena",
        icon = ICONS.arenaGeneric,
        genericIcons = {
            default = ICONS.arenaGeneric,
            complete = ICONS.arenaGenericComplete,
            incomplete = ICONS.arenaGenericIncomplete,
        },
        genericChallenge = true,
        activityIds = { 184 },
        dynamicPinType = "arena",
        match = {
            "complete 1 arena",
            "complete an arena",
        },
    },
    {
        key = "u50_talk_to_banker",
        label = "Talk to a Banker",
        icon = ICONS.bankGeneric,
        activityIds = { 570, 721 },
        dynamicPinType = "bank",
        match = {
            "talk to a banker",
            "banker",
        },
    },
    {
        key = "u50_delve_bosses",
        label = "Kill Delve Bosses",
        icon = ICONS.delveGeneric,
        genericIcons = {
            default = ICONS.delveGeneric,
            complete = ICONS.delveGenericComplete,
            incomplete = ICONS.delveGenericIncomplete,
        },
        genericChallenge = true,
        activityIds = { 154, 634, 722 },
        dynamicPinType = "delve",
        match = {
            "delve boss",
            "delve bosses",
        },
    },
    {
        key = "u50_mundus_stones",
        label = "Acquire Mundus Boons",
        icon = ICONS.mundusGeneric,
        activityIds = { 168, 723 },
        dynamicPinType = "mundus",
        match = {
            "mundus stone",
            "mundus boon",
        },
    },
    {
        key = "u50_world_events",
        label = "World Events",
        icon = ICONS.worldEventGeneric,
        bonusIcon = ICONS.worldEvent,
        bonusZoneIds = {
            [3] = true,
        },
        genericIcons = {
            default = ICONS.worldEventGenericIncomplete,
            complete = ICONS.worldEventGenericComplete,
            incomplete = ICONS.worldEventGenericIncomplete,
            undiscovered = ICONS.worldEventGenericIncomplete,
        },
        genericChallenge = true,
        activityIds = { 187, 292, 293, 295, 296, 597, 724, 757 },
        dynamicPinType = "worldEvent",
        match = {
            "dark anchor",
            "incursion",
            "world event",
            "overland incursion",
            "abyssal geyser",
            "harrowstorm",
            "oblivion portal",
        },
    },
    {
        key = "u50_guild_daily_quests",
        label = "Guild Daily Quests",
        icon = ICONS.thievesGuild,
        activityIds = { 381 },
        dynamicPinType = "thievesGuild",
        match = {
            "guild daily quest",
            "guild daily quests",
        },
    },
    {
        key = "u50_fighters_guild_quest",
        label = "Fighters Guild Quest",
        icon = ICONS.fightersGuildGeneric,
        activityIds = { 594, 725 },
        dynamicPinType = "fightersGuild",
        match = {
            "fighters guild quest",
        },
    },
    {
        key = "u50_mages_guild_quest",
        label = "Mages Guild Quest",
        icon = ICONS.magesGuildGeneric,
        activityIds = { 595, 726 },
        dynamicPinType = "magesGuild",
        match = {
            "mages guild quest",
        },
    },
    {
        key = "u50_guild_trader",
        label = "Visit a Guild Trader",
        icon = ICONS.guildTraderGeneric,
        activityIds = { 372, 603, 729 },
        dynamicPinType = "guildTrader",
        match = {
            "guild trader",
        },
    },
    {
        key = "u50_undaunted_quest",
        label = "Undaunted Quest",
        icon = ICONS.undauntedGeneric,
        activityIds = { 596, 730 },
        dynamicPinType = "undaunted",
        match = {
            "undaunted quest",
        },
    },
    {
        key = "u50_public_dungeon_bosses",
        label = "Public Dungeons",
        icon = ICONS.publicDungeon,
        genericIcons = {
            default = ICONS.publicDungeon,
            complete = ICONS.publicDungeonComplete,
            incomplete = ICONS.publicDungeonIncomplete,
        },
        genericChallenge = true,
        activityIds = { 153, 183, 412, 634, 739, 746, 749 },
        dynamicPinType = "publicDungeon",
        match = {
            "public dungeon boss",
            "public dungeon bosses",
        },
    },
    {
        key = "u50_dynamic_encounters",
        label = "Dynamic Encounters",
        icon = ICONS.dynamicEncounterGeneric,
        activityIds = { 755 },
        dynamicPinType = "dynamicEncounter",
        match = {
            "dynamic encounter",
            "dynamic encounters",
        },
    },
    {
        key = "u50_fungal_grotto_1",
        label = "Fungal Grotto I",
        icon = ICONS.groupDungeon,
        activityIds = { 254, 732 },
        match = {
            "fungal grotto i",
            "fungal grotto 1",
        },
        pins = {
            { type = "poi", zoneId = 41, poiIndex = 34, label = "Fungal Grotto I" },
        },
    },
    {
        key = "complete_dungeon",
        label = "Complete 1 Dungeon",
        icon = ICONS.groupDungeonGeneric,
        bonusIcon = ICONS.groupDungeon,
        bonusZoneIds = {
            [3] = true,
        },
        genericIcons = {
            default = ICONS.groupDungeonGeneric,
            complete = ICONS.groupDungeonGenericComplete,
            incomplete = ICONS.groupDungeonGenericIncomplete,
        },
        genericChallenge = true,
        activityIds = { 182, 318, 446, 447, 448, 449, 450, 605, 671, 761 },
        dynamicPinType = "groupDungeon",
        match = {
            "complete 1 dungeon",
            "complete a dungeon",
            "complete dungeon",
            "group dungeon",
            "complete 1 group dungeon",
            "complete group dungeon",
            "glenumbra and beyond",
        },
    },
    {
        key = "complete_trial",
        label = "Complete 1 Trial",
        icon = ICONS.trialGeneric,
        genericIcons = {
            default = ICONS.trialGeneric,
            complete = ICONS.trialGenericComplete,
            incomplete = ICONS.trialGenericIncomplete,
        },
        genericChallenge = true,
        activityIds = { 185, 319, 413, 451, 452, 453, 454 },
        dynamicPinType = "trial",
        match = {
            "complete 1 trial",
            "complete a trial",
            "trial boss",
            "trial bosses",
        },
    },
})
