local Addon = LarvalTearMod
local LTM_UI_DIALOGS = Addon.UI.Dialogs

LTM_UI_DIALOGS.definitions = {
    OVERWRITE_CARD_PICKER = {
        dialogId = "OVERWRITE_CARD_PICKER",
        style = "overwrite_picker",
        titleTextKey = "dialog.overwrite_card.title",
        bodyTextKey = "dialog.overwrite_card.body",
    },
    DELETE_CARD_CONFIRM = {
        dialogId = "DELETE_CARD_CONFIRM",
        style = "confirm",
        titleTextKey = "dialog.delete_card.title",
        bodyTextKey = "dialog.delete_card.body",
        confirmTextKey = "common.delete",
        cancelTextKey = "common.cancel",
    },
    DELETE_PAGE_CONFIRM = {
        dialogId = "DELETE_PAGE_CONFIRM",
        style = "confirm",
        titleTextKey = "dialog.delete_page.title",
        bodyTextKey = "dialog.delete_page.body",
        confirmTextKey = "common.delete",
        cancelTextKey = "common.cancel",
    },
    REORDER_PAGES = {
        dialogId = "REORDER_PAGES",
        style = "page_reorder",
        titleTextKey = "dialog.reorder_pages.title",
        bodyTextKey = "dialog.reorder_pages.body",
        confirmTextKey = "common.save",
        cancelTextKey = "common.cancel",
    },
    REORDER_BUILDS = {
        dialogId = "REORDER_BUILDS",
        style = "build_reorder",
        titleTextKey = "dialog.reorder_builds.title",
        bodyTextKey = "dialog.reorder_builds.body",
        confirmTextKey = "common.save",
        cancelTextKey = "common.cancel",
    },
    MOVE_BUILD_TO_PAGE = {
        dialogId = "MOVE_BUILD_TO_PAGE",
        style = "page_picker",
        titleTextKey = "dialog.move_build.title",
        bodyTextKey = "dialog.move_build.body",
        confirmTextKey = "common.save",
        cancelTextKey = "common.cancel",
    },
    RENAME_CARD_INPUT = {
        dialogId = "RENAME_CARD_INPUT",
        style = "input",
        titleTextKey = "dialog.rename_card.title",
        bodyTextKey = "dialog.rename_card.body",
        confirmTextKey = "common.rename",
        cancelTextKey = "common.cancel",
        inputLabelTextKey = "dialog.rename_card.input",
    },
    RENAME_PAGE_INPUT = {
        dialogId = "RENAME_PAGE_INPUT",
        style = "input",
        titleTextKey = "dialog.rename_page.title",
        bodyTextKey = "dialog.rename_page.body",
        confirmTextKey = "common.rename",
        cancelTextKey = "common.cancel",
        inputLabelTextKey = "dialog.rename_page.input",
    },
    APPLY_START_CONFIRM = {
        dialogId = "APPLY_START_CONFIRM",
        style = "confirm",
        titleTextKey = "dialog.apply_start_confirm.title",
        bodyTextKey = "dialog.apply_start_confirm.body",
        confirmTextKey = "common.apply",
        cancelTextKey = "common.cancel",
    },
    ROUTE_B_BUDGET_SHORT_CONFIRM = {
        dialogId = "ROUTE_B_BUDGET_SHORT_CONFIRM",
        style = "confirm",
        titleTextKey = "dialog.route_b_budget_short.title",
        bodyTextKey = "dialog.route_b_budget_short.body",
        budgetSummaryTextKeys = {
            "dialog.skill_budget.summary.current",
            "dialog.skill_budget.summary.refund",
            "dialog.skill_budget.summary.active_required",
            "dialog.skill_budget.summary.total_required",
        },
        budgetExpectedTextKey = "dialog.skill_budget.expected",
        confirmTextKey = "common.apply",
        cancelTextKey = "common.cancel",
    },
    SKILL_BUDGET_SHORT_CONFIRM = {
        dialogId = "SKILL_BUDGET_SHORT_CONFIRM",
        style = "confirm",
        titleTextKey = "dialog.route_b_budget_short.title",
        bodyTextKey = "dialog.skill_budget_short.body",
        budgetSummaryTextKeys = {
            "dialog.skill_budget.summary.current",
            "dialog.skill_budget.summary.refund",
            "dialog.skill_budget.summary.active_required",
            "dialog.skill_budget.summary.total_required",
        },
        budgetExpectedTextKey = "dialog.skill_budget.expected",
        confirmTextKey = "common.apply",
        cancelTextKey = "common.cancel",
    },
    CURRENT_SKILL_SNAPSHOT = {
        dialogId = "CURRENT_SKILL_SNAPSHOT",
        style = "snapshot_view",
        titleTextKey = "dialog.current_skill_snapshot.title",
        bodyTextKey = "dialog.current_skill_snapshot.body",
        confirmTextKey = "common.close",
    },
    QUICKSLOT_MISSING_CONFIRM = {
        dialogId = "QUICKSLOT_MISSING_CONFIRM",
        style = "confirm",
        titleTextKey = "dialog.quickslot_missing.title",
        bodyTextKey = "dialog.quickslot_missing.body",
        confirmTextKey = "common.apply",
        cancelTextKey = "common.cancel",
    },
    QUICKSLOT_RENAME_INPUT = {
        dialogId = "QUICKSLOT_RENAME_INPUT",
        style = "input",
        titleTextKey = "dialog.quickslot_rename.title",
        bodyTextKey = "dialog.quickslot_rename.body",
        confirmTextKey = "common.rename",
        cancelTextKey = "common.cancel",
        inputLabelTextKey = "dialog.quickslot_rename.input",
    },
    ALCHEMY_RECIPE_RENAME_INPUT = {
        dialogId = "ALCHEMY_RECIPE_RENAME_INPUT",
        style = "input",
        titleTextKey = "dialog.alchemy_recipe_rename.title",
        bodyTextKey = "dialog.alchemy_recipe_rename.body",
        confirmTextKey = "common.rename",
        cancelTextKey = "common.cancel",
        inputLabelTextKey = "dialog.alchemy_recipe_rename.input",
    },
    ENCHANT_RECIPE_RENAME_INPUT = {
        dialogId = "ENCHANT_RECIPE_RENAME_INPUT",
        style = "input",
        titleTextKey = "dialog.enchant_recipe_rename.title",
        bodyTextKey = "dialog.enchant_recipe_rename.body",
        confirmTextKey = "common.rename",
        cancelTextKey = "common.cancel",
        inputLabelTextKey = "dialog.enchant_recipe_rename.input",
    },
    SCRIBING_RECIPE_RENAME_INPUT = {
        dialogId = "SCRIBING_RECIPE_RENAME_INPUT",
        style = "input",
        titleTextKey = "dialog.scribing_recipe_rename.title",
        bodyTextKey = "dialog.scribing_recipe_rename.body",
        confirmTextKey = "common.rename",
        cancelTextKey = "common.cancel",
        inputLabelTextKey = "dialog.scribing_recipe_rename.input",
    },
}

function LTM_UI_DIALOGS:Get(dialogId)
    return self.definitions[dialogId]
end
