-- -----------------------------------------------------------------------------
--  LuiExtended                                                               --
--  Distributed under The MIT License (MIT) (see LICENSE file)                --
-- -----------------------------------------------------------------------------

--- Registry of ability ids whose English raw name contains Off Balance / Off-Balance.
--- @class (partial) LuiData
local LuiData = LuiData

local Data = LuiData.Data
local Effects = Data.Effects

Effects.OffBalanceImmunityAbilityId = 134599

--- @class OffBalanceRegistryEntry
--- @field id integer
--- @field rawName string

--- @type OffBalanceRegistryEntry[]
Effects.OffBalanceAbilityRegistry =
{
    { id = 1347,   rawName = "Off-Balance"                    },
    { id = 2727,   rawName = "Off-Balance"                    },
    { id = 3144,   rawName = "Off Balance Enemy"              },
    { id = 3464,   rawName = "Remove Off-Balance"             },
    { id = 4508,   rawName = "Off-Balance"                    },
    { id = 4839,   rawName = "Perma Set Off Balance Target"   },
    { id = 5805,   rawName = "Off Balance"                    },
    { id = 6150,   rawName = "Off Balance"                    },
    { id = 7534,   rawName = "Off-Balance"                    },
    { id = 8392,   rawName = "Off-Balance"                    },
    { id = 11474,  rawName = "Off Balance"                    },
    { id = 14062,  rawName = "Off Balance"                    },
    { id = 14883,  rawName = "Off-Balance"                    },
    { id = 14884,  rawName = "Off-Balance"                    },
    { id = 16825,  rawName = "Off Balance Exploit"            },
    { id = 18147,  rawName = "Off-Balance Self"               },
    { id = 18793,  rawName = "Off Balance Exploit"            },
    { id = 20806,  rawName = "Off Balance"                    },
    { id = 25256,  rawName = "Off Balance"                    },
    { id = 29598,  rawName = "Off Balance"                    },
    { id = 34733,  rawName = "Off Balance"                    },
    { id = 34737,  rawName = "Off Balance"                    },
    { id = 37152,  rawName = "Off Balance"                    },
    { id = 39077,  rawName = "Off Balance"                    },
    { id = 39695,  rawName = "Off-Balance Self"               },
    { id = 44364,  rawName = "Off-Balance Exploit"            },
    { id = 45834,  rawName = "Off Balance"                    },
    { id = 45902,  rawName = "Off Balance"                    },
    { id = 61956,  rawName = "Off-Balance Timer"              },
    { id = 61961,  rawName = "Perma Set Off Balance Target"   },
    { id = 61980,  rawName = "Off-Balance"                    },
    { id = 62968,  rawName = "Off Balance"                    },
    { id = 62988,  rawName = "Off Balance"                    },
    { id = 63108,  rawName = "Off-Balance"                    },
    { id = 64676,  rawName = "MQ1 Tutorial Perma Off-Balance" },
    { id = 64677,  rawName = "MQ1 Tutorial Perma Off-Balance" },
    { id = 70054,  rawName = "Off Balance"                    },
    { id = 71877,  rawName = "Off Balance"                    },
    { id = 72279,  rawName = "Off Balance"                    },
    { id = 75214,  rawName = "Off Balance"                    },
    { id = 89681,  rawName = "Off-Balance"                    },
    { id = 92262,  rawName = "Off-Balance Timer"              },
    { id = 92263,  rawName = "Perma Set Off Balance Target"   },
    { id = 92264,  rawName = "MQ1 Tutorial Perma Off-Balance" },
    { id = 92265,  rawName = "Off-Balance"                    },
    { id = 92266,  rawName = "MQ1 Tutorial Perma Off-Balance" },
    { id = 99535,  rawName = "Off-Balance"                    },
    { id = 100582, rawName = "Off Balance"                    },
    { id = 100686, rawName = "Off-Balance"                    },
    { id = 100687, rawName = "Off-Balance"                    },
    { id = 100689, rawName = "Off-Balance"                    },
    { id = 100690, rawName = "Off-Balance"                    },
    { id = 100694, rawName = "Off-Balance"                    },
    { id = 104012, rawName = "Off Balance"                    },
    { id = 116998, rawName = "Off-Balance"                    },
    { id = 117008, rawName = "Off-Balance"                    },
    { id = 117009, rawName = "Off-Balance"                    },
    { id = 117010, rawName = "Off-Balance"                    },
    { id = 117011, rawName = "Off-Balance"                    },
    { id = 117292, rawName = "Off Balance"                    },
    { id = 120014, rawName = "Off Balance"                    },
    { id = 121024, rawName = "Off-Balance"                    },
    { id = 121026, rawName = "Off-Balance"                    },
    { id = 121031, rawName = "Off-Balance"                    },
    { id = 121040, rawName = "Off-Balance"                    },
    { id = 121042, rawName = "Off-Balance"                    },
    { id = 121123, rawName = "Off-Balance"                    },
    { id = 121124, rawName = "Off-Balance"                    },
    { id = 125750, rawName = "Off Balance"                    },
    { id = 126526, rawName = "Off-Balance"                    },
    { id = 126567, rawName = "Off-Balance Exploit"            },
    { id = 126568, rawName = "Off-Balance Exploit"            },
    { id = 126569, rawName = "Off-Balance Exploit"            },
    { id = 126570, rawName = "Off-Balance Exploit"            },
    { id = 126571, rawName = "Off-Balance Exploit"            },
    { id = 126572, rawName = "Off-Balance Exploit"            },
    { id = 126573, rawName = "Off-Balance"                    },
    { id = 128752, rawName = "Off-Balance"                    },
    { id = 130129, rawName = "Off Balance"                    },
    { id = 130139, rawName = "Off Balance"                    },
    { id = 130145, rawName = "Off Balance"                    },
    { id = 131562, rawName = "Off Balance"                    },
    { id = 134599, rawName = "Off Balance Immunity"           },
    { id = 137257, rawName = "Off Balance"                    },
    { id = 137312, rawName = "Off Balance"                    },
    { id = 144658, rawName = "Off-Balance Exploit"            },
    { id = 154579, rawName = "Off Balance"                    },
    { id = 156183, rawName = "Off Balance"                    },
    { id = 163593, rawName = "Off Balance"                    },
    { id = 164731, rawName = "Off Balance"                    },
    { id = 186482, rawName = "Off Balance"                    },
    { id = 192997, rawName = "Off-Balance"                    },
    { id = 208859, rawName = "Off Balance"                    },
    { id = 211496, rawName = "Off Balance"                    },
    { id = 212853, rawName = "Off Balance"                    },
    { id = 214432, rawName = "Off Balance"                    },
    { id = 218822, rawName = "Off-Balance"                    },
    { id = 230828, rawName = "Off-Balance"                    },
    { id = 236061, rawName = "Player Off Balance"             },
    { id = 240504, rawName = "Off Balance"                    },
    { id = 241340, rawName = "Off Balance"                    },
    { id = 253689, rawName = "Off-Balance"                    },
    { id = 256815, rawName = "Off Balance"                    },
}
