---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cjdem.
--- DateTime: 4/9/2024 4:13 PM
---
-- ZOS Classes
local ZO_ColorDef = ZO_ColorDef
local RPFinder = ROLE_PLAY_FINDER_MANAGER

local colorsRGB = {
    aliceblue = {240, 248, 255},
    antiquewhite = {250, 235, 215},
    aqua = { 0, 255, 255},
    aquamarine = {127, 255, 212},
    azure = {240, 255, 255},
    beige = {245, 245, 220},
    bisque = {255, 228, 196},
    black = { 0, 0, 0},
    blanchedalmond = {255, 235, 205},
    blue = { 0, 0, 255},
    blueviolet = {138, 43, 226},
    brown = {165, 42, 42},
    burlywood = {222, 184, 135},
    cadetblue = { 95, 158, 160},
    chartreuse = {127, 255, 0},
    chocolate = {210, 105, 30},
    coral = {255, 127, 80},
    cornflowerblue = {100, 149, 237},
    cornsilk = {255, 248, 220},
    crimson = {220, 20, 60},
    cyan = { 0, 255, 255},
    darkblue = { 0, 0, 139},
    darkcyan = { 0, 139, 139},
    darkgoldenrod = {184, 134, 11},
    darkgray = {169, 169, 169},
    darkgreen = { 0, 100, 0},
    darkgrey = {169, 169, 169},
    darkkhaki = {189, 183, 107},
    darkmagenta = {139, 0, 139},
    darkolivegreen = { 85, 107, 47},
    darkorange = {255, 140, 0},
    darkorchid = {153, 50, 204},
    darkred = {139, 0, 0},
    darksalmon = {233, 150, 122},
    darkseagreen = {143, 188, 143},
    darkslateblue = { 72, 61, 139},
    darkslategray = { 47, 79, 79},
    darkslategrey = { 47, 79, 79},
    darkturquoise = { 0, 206, 209},
    darkviolet = {148, 0, 211},
    deeppink = {255, 20, 147},
    deepskyblue = { 0, 191, 255},
    dimgray = {105, 105, 105},
    dimgrey = {105, 105, 105},
    dodgerblue = { 30, 144, 255},
    firebrick = {178, 34, 34},
    floralwhite = {255, 250, 240},
    forestgreen = { 34, 139, 34},
    fuchsia = {255, 0, 255},
    gainsboro = {220, 220, 220},
    ghostwhite = {248, 248, 255},
    gold = {255, 215, 0},
    goldenrod = {218, 165, 32},
    gray = {128, 128, 128},
    grey = {128, 128, 128},
    green = { 0, 128, 0},
    greenyellow = {173, 255, 47},
    honeydew = {240, 255, 240},
    hotpink = {255, 105, 180},
    indianred = {205, 92, 92},
    indigo = { 75, 0, 130},
    ivory = {255, 255, 240},
    khaki = {240, 230, 140},
    lavender = {230, 230, 250},
    lavenderblush = {255, 240, 245},
    lawngreen = {124, 252, 0},
    lemonchiffon = {255, 250, 205},
    lightblue = {173, 216, 230},
    lightcoral = {240, 128, 128},
    lightcyan = {224, 255, 255},
    lightgoldenrodyellow = {250, 250, 210},
    lightgray = {211, 211, 211},
    lightgreen = {144, 238, 144},
    lightgrey = {211, 211, 211},
    lightpink = {255, 182, 193},
    lightsalmon = {255, 160, 122},
    lightseagreen = { 32, 178, 170},
    lightskyblue = {135, 206, 250},
    lightslategray = {119, 136, 153},
    lightslategrey = {119, 136, 153},
    lightsteelblue = {176, 196, 222},
    lightyellow = {255, 255, 224},
    lime = { 0, 255, 0},
    limegreen = { 50, 205, 50},
    linen = {250, 240, 230},
    magenta = {255, 0, 255},
    maroon = {128, 0, 0},
    mediumaquamarine = {102, 205, 170},
    mediumblue = { 0, 0, 205},
    mediumorchid = {186, 85, 211},
    mediumpurple = {147, 112, 219},
    mediumseagreen = { 60, 179, 113},
    mediumslateblue = {123, 104, 238},
    mediumspringgreen = { 0, 250, 154},
    mediumturquoise = { 72, 209, 204},
    mediumvioletred = {199, 21, 133},
    midnightblue = { 25, 25, 112},
    mintcream = {245, 255, 250},
    mistyrose = {255, 228, 225},
    moccasin = {255, 228, 181},
    navajowhite = {255, 222, 173},
    navy = { 0, 0, 128},
    oldlace = {253, 245, 230},
    olive = {128, 128, 0},
    olivedrab = {107, 142, 35},
    orange = {255, 165, 0},
    orangered = {255, 69, 0},
    orchid = {218, 112, 214},
    palegoldenrod = {238, 232, 170},
    palegreen = {152, 251, 152},
    paleturquoise = {175, 238, 238},
    palevioletred = {219, 112, 147},
    papayawhip = {255, 239, 213},
    peachpuff = {255, 218, 185},
    peru = {205, 133, 63},
    pink = {255, 192, 203},
    plum = {221, 160, 221},
    powderblue = {176, 224, 230},
    purple = {128, 0, 128},
    red = {255, 0, 0},
    rosybrown = {188, 143, 143},
    royalblue = { 65, 105, 225},
    saddlebrown = {139, 69, 19},
    salmon = {250, 128, 114},
    sandybrown = {244, 164, 96},
    seagreen = { 46, 139, 87},
    seashell = {255, 245, 238},
    sienna = {160, 82, 45},
    silver = {192, 192, 192},
    skyblue = {135, 206, 235},
    slateblue = {106, 90, 205},
    slategray = {112, 128, 144},
    slategrey = {112, 128, 144},
    snow = {255, 250, 250},
    springgreen = { 0, 255, 127},
    steelblue = { 70, 130, 180},
    tan = {210, 180, 140},
    teal = { 0, 128, 128},
    thistle = {216, 191, 216},
    tomato = {255, 99, 71},
    turquoise = { 64, 224, 208},
    violet = {238, 130, 238},
    wheat = {245, 222, 179},
    white = {255, 255, 255},
    whitesmoke = {245, 245, 245},
    yellow = {255, 255, 0},
    yellowgreen = {154, 205, 50}
}

local function rgbToHex(rgb)
    --    local hexadecimal = '0X'
    local hexadecimal = ''

    for key, value in pairs(rgb) do
        local hex = ''

        while(value > 0)do
            local index = math.fmod(value, 16) + 1
            value = math.floor(value / 16)
            hex = string.sub('0123456789ABCDEF', index, index) .. hex
        end

        if(string.len(hex) == 0)then
            hex = '00'

        elseif(string.len(hex) == 1)then
            hex = '0' .. hex
        end

        hexadecimal = hexadecimal .. hex
    end

    return hexadecimal
end

local hexTable = {}

local function buildHexTable()
    for k, rgb in pairs(colorsRGB) do
        local hexadecimal = rgbToHex(rgb)
        hexTable[k] = hexadecimal
    end
end

local Colors = {}

function Colors.FromHex(hex)
    local c = ZO_ColorDef:New(hex)
    return c
end

function Colors.UnpackRGBA(color)
    if not colorsRGB or not colorsRGB[color] then
        return 0, 0, 0, 1
    end

    --df("Returning color: %s", color)
    return colorsRGB[color][1] / 255, colorsRGB[color][2] / 255, colorsRGB[color][3] / 255, colorsRGB[color][4] or 1
end

function Colors.ToHex(color)
    return hexTable[color]
end

function Colors.ToColorDef(color)
    if not colorsRGB then
        return ZO_ColorDef:New(0, 0, 0, 0)
    end
    return ZO_ColorDef:New(colorsRGB[color][1] / 255, colorsRGB[color][2] / 255, colorsRGB[color][3] / 255, colorsRGB[color][4] or 1)
end

local function IsColor( c )
    return	"table" == type( c ) and
            "number" == type( c.r ) and
            "number" == type( c.g ) and
            "number" == type( c.b ) and
            "number" == type( c.a )
end

local function IsGradient( c )
    return	"table" == type( c ) and
            IsColor( c.tl ) and
            IsColor( c.tr ) and
            IsColor( c.bl ) and
            IsColor( c.br )
end

local function CreateColor( r, g, b, a )
    return { r = r, g = g, b = b, a = a,
             UnpackRGBA = function(self)
                 return self.r, self.g, self.b, self.a
             end
    }
end

local function FadeColor( c, colorCoeff, alphaCoeff )
    colorCoeff = colorCoeff or 1
    alphaCoeff = alphaCoeff or 0

    if IsGradient( c ) then
        return CreateColor( colorCoeff * c.tl.r, colorCoeff * c.tl.g, colorCoeff * c.tl.b, alphaCoeff * c.tl.a )
    else
        return CreateColor( colorCoeff * c.r, colorCoeff * c.g, colorCoeff * c.b, alphaCoeff * c.a )
    end
end

local clone = ZO_DeepTableCopy

local function CreateGradient( topLeft, topRight, bottomLeft, bottomRight )
    return { tl = clone( topLeft ), tr = clone( topRight ), bl = clone( bottomLeft ), br = clone( bottomRight ) }
end

local function CreateGradientFade( color, directions )
    local c

    if IsGradient( color ) then
        c = CreateGradient( color.tl, color.tr, color.bl, color.br )
    else
        c = CreateGradient( color, color, color, color )
    end

    if bit.Has( directions, bit.New( 1 ) ) then c.tl = FadeColor( c.tl ) end
    if bit.Has( directions, bit.New( 2 ) ) then c.tr = FadeColor( c.tr ) end
    if bit.Has( directions, bit.New( 3 ) ) then c.bl = FadeColor( c.bl ) end
    if bit.Has( directions, bit.New( 4 ) ) then c.br = FadeColor( c.br ) end

    return c
end

local function LerpColor( cout, c1, c2, interval )
    if IsGradient( c1 ) then
        local tl1, tr1, bl1, br1 = c1.tl, c1.tr, c1.bl, c1.br
        local tl2, tr2, bl2, br2 = c2.tl, c2.tr, c2.bl, c2.br

        if not cout then
            cout = { tl = clone( Colors.Black ), tr = clone( Colors.Black ), bl = clone( Colors.Black ), br = clone( Colors.Black ) }
        elseif not cout.tl then
            cout.tl, cout.tr, cout.bl, cout.br = clone( Colors.Black ), clone( Colors.Black ), clone( Colors.Black ), clone( Colors.Black )
        end

        cout.tl.r, cout.tl.g, cout.tl.b, cout.tl.a = zo_lerp( tl1.r, tl2.r, interval ), zo_lerp( tl1.g, tl2.g, interval ), zo_lerp( tl1.b, tl2.b, interval ), zo_lerp( tl1.a, tl2.a, interval )
        cout.tr.r, cout.tr.g, cout.tr.b, cout.tr.a = zo_lerp( tr1.r, tr2.r, interval ), zo_lerp( tr1.g, tr2.g, interval ), zo_lerp( tr1.b, tr2.b, interval ), zo_lerp( tr1.a, tr2.a, interval )
        cout.bl.r, cout.bl.g, cout.bl.b, cout.bl.a = zo_lerp( bl1.r, bl2.r, interval ), zo_lerp( bl1.g, bl2.g, interval ), zo_lerp( bl1.b, bl2.b, interval ), zo_lerp( bl1.a, bl2.a, interval )
        cout.br.r, cout.br.g, cout.br.b, cout.br.a = zo_lerp( br1.r, br2.r, interval ), zo_lerp( br1.g, br2.g, interval ), zo_lerp( br1.b, br2.b, interval ), zo_lerp( br1.a, br2.a, interval )
    else
        if not cout then
            cout = { }
        elseif cout.tl then
            cout.tl, cout.tr, cout.bl, cout.br = nil, nil, nil, nil
        end

        cout.r, cout.g, cout.b, cout.a = zo_lerp( c1.r, c2.r, interval ), zo_lerp( c1.g, c2.g, interval ), zo_lerp( c1.b, c2.b, interval ), zo_lerp( c1.a, c2.a, interval )
    end
end

local function SetVertexColor( control, vertex, color, filter )
    if "userdata" ~= type( control ) or "number" ~= type( vertex ) or "table" ~= type( color ) or not control.SetVertexColors then
        return
    end

    if "table" ~= type( filter ) then
        filter = { }
    end

    control:SetVertexColors( vertex, color.r * ( filter.r or 1 ), color.g * ( filter.g or 1 ), color.b * ( filter.b or 1 ), color.a * ( filter.a or 1 ) )
end

local function SetColor( control, color, filter )
    if "userdata" ~= type( control ) or "table" ~= type( color ) then
        return
    end

    if "table" ~= type( filter ) then
        filter = { }
    end

    if color.tl or color.tr or color.bl or color.br then
        SetVertexColor( control, 1, color.tl, filter )
        SetVertexColor( control, 2, color.tr, filter )
        SetVertexColor( control, 4, color.bl, filter )
        SetVertexColor( control, 8, color.br, filter )
    else
        control:SetColor( ( color.r or 0 ) * ( filter.r or 1 ), ( color.g or 1 ) * ( filter.g or 1 ), ( color.b or 1 ) * ( filter.b or 1 ), ( color.a or 1 ) * ( filter.a or 1 ) )
    end
end


function Colors.Create(color)
    if not colorsRGB then
        return RPFinder.Colors.CreateColor(0, 0, 0, 0)
    end
    assert(colorsRGB[color], "Color not found: " .. color)
    return RPFinder.Resources.Colors.CreateColor(colorsRGB[color][1] / 255, colorsRGB[color][2] / 255, colorsRGB[color][3] / 255, colorsRGB[color][4] or 1)
end

function Colors.Colorize(color, text)
    if not colorsRGB then
        local color = ZO_ColorDef:New(RPFinder.Colors.CreateColor(0, 0, 0, 0))
        return color:Colorize(text)
    end
    assert(colorsRGB[color], "Color not found: " .. color)
    local color = ZO_ColorDef:New(RPFinder.Resources.Colors.CreateColor(colorsRGB[color][1] / 255, colorsRGB[color][2] / 255, colorsRGB[color][3] / 255, colorsRGB[color][4] or 1))
    return color:Colorize(text)
end

Colors.IsColor = IsColor
Colors.IsGradient = IsGradient

Colors.CreateColor = CreateColor
Colors.CreateGradient = CreateGradient
Colors.CreateGradientFade = CreateGradientFade
Colors.LerpColor = LerpColor
Colors.SetColor = SetColor
Colors.SetVertexColor = SetVertexColor

RPFinder.Utils.IsColor = IsColor
RPFinder.Utils.IsGradient = IsGradient

RPFinder.Utils.CreateColor = CreateColor
RPFinder.Utils.CreateGradient = CreateGradient
RPFinder.Utils.CreateGradientFade = CreateGradientFade
RPFinder.Utils.LerpColor = LerpColor
RPFinder.Utils.SetColor = SetColor
RPFinder.Utils.SetVertexColor = SetVertexColor

RPFinder.Resources.Colors = Colors

buildHexTable()