---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cjdem.
--- DateTime: 4/9/2024 4:25 PM
---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cjdem.
--- DateTime: 4/9/2024 4:08 PM
---
--[[
	Carbon for Lua
	#class Debug
	#inherits OOP.Object
	#description {
		Signals detailed, strongly-typed error conditions.
	}
	Ported to ESO for RPFinder by KaT
]]

--[[
	#property public @string Debug.Message {
		An error message explaining the Debug.
	}
]]
local RPFinder = ROLE_PLAY_FINDER_MANAGER
RPFinder.DebugLevel = 1

local Debug = ZO_Object:Subclass()

--[[#method 1 {
	$typical_constructor(Debug(@string message))
		required message: The message to initialize the Debug with.
	Creates a new generic Debug with the given message.
}]]
function Debug:New(message)
    local obj = ZO_Object.New(self)
    self.Variables = {}
    if CodeGuard then
        self.Variables.IsDev = CodeGuard.IsDev
    end
    obj:Initialize(message)
    return obj
end

function Debug:Initialize(message)
    self.Message = message or self.Message or self.Variables.Message
    self.Warnings = self.Warnings or {}
    self.Status = self.Status or {}
    -- TODO: Add to saved vars
    self.Logs = self.Logs or {}
    self.Todo = self.Todo or {}
end

--[[#method {
	object public @void Debug:Throw([@uint level])
		optional level: An optional parameter passed onto Lua's error function.
	Throws the Debug as a traditional Lua error.
}]]
function Debug:Throw(level, msg, ...)
    msg = msg or self.Message
    msg = string.format(msg, ...)
    error(msg, (level or 0) + 1)
end

--[[#method {
	object public @void Debug:ThrowIf(@bool condition, [@uint level])
		required condition: The condition determining whether this Debug should throw.
		optional level: Passed onto Lua's error method determining the level of the error.
	Throws the Debug if a given condition is truthy. Similar to Lua's `assert`.
}]]
function Debug:ThrowIf(condition, level, msg, ...)
    if (condition) then
        self:Throw(level, msg, ...)
    end
end

function Debug:Emit(message)
    CHAT_ROUTER:AddSystemMessage(message)
end

function Debug:Echo(format, ...)
    local message = string.format(format, ...)
    return self:Emit(message)
end

function Debug:ColorEcho(color, format, ...)
    --df("Echoing color: %s", color)
    local passedColor = color
    local color = RPFinder.Resources.Colors.ToHex(color)
    --df("Echoing color: %s", color)
    local newFormat = format
    if color then
        newFormat = "|C" .. color .. format .. "|r"
    else
        df("Color '%s' not found, using default", passedColor)
    end
    return self:Echo(newFormat, ...)
end

function Debug:AddWarning(format, ...)
    local warning = string.format(format, ...)
    table.insert(self.Warnings, warning)
end

function Debug:Log(level, msg)
    local log = {Level = level,
                 Message = msg,
    }
    table.insert(self.Logs, log)
end

function Debug:Trace(format, ...)
    local msg = string.format(format, ...)
    self:Log(1, msg)
    if RPFinder.DebugLevel > 1 then
        return
    end
    msg = "{Trace} " .. msg
    return self:ColorEcho("lightgreen", msg)
end

function Debug:Debug(format, ...)
    if not RPFinder.Variables.IsDev then
        return
    end
    local msg = string.format(format, ...)
    self:Log(1, msg)
    if RPFinder.DebugLevel > 1 then
        return
    end
    msg = "{Debug} " .. msg
    return self:ColorEcho("lightgreen", msg)
end

function Debug:TODO(format, ...)
    if not RPFinder.Variables.IsDev then
        return
    end
    local msg = string.format(format, ...)
    self:Log(1, msg)
    if RPFinder.DebugLevel > 1 then
        return
    end
    msg = "{TODO} " .. msg
    table.insert(self.Todo, msg)
    return self:ColorEcho("darksalmon", msg)
end

-- Our version of return
RPFinder.Debug = Debug:New()

RPFinder.ColorEcho = RPFinder.Debug.ColorEcho
RPFinder.Echo = RPFinder.Debug.Echo
RPFinder.Emit = RPFinder.Debug.Emit
RPFinder.Trace = RPFinder.Debug.Trace
