---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cjdem.
--- DateTime: 4/5/2024 4:01 PM
---

local showSpoofData = false

local GROUP_FINDER_SEARCH_MANAGER = GROUP_FINDER_SEARCH_MANAGER
local GROUP_FINDER_KEYBOARD = GROUP_FINDER_KEYBOARD
local ADDON_NAME = "RPFinder"

local LOCATION_TYPE_WORLD = 0
local LOCATION_TYPE_HOUSING = 1

local GROUP_SHOW_ALL = 0
local GROUP_SHOW_ZONE = 1
local GROUP_SHOW_HOUSING = 2

local noAutoBuild = true

-- ZOS Globals to local
local GetCurrentZoneHouseId = GetCurrentZoneHouseId
local GetCurrentHouseOwner = GetCurrentHouseOwner
local GetPlayerLocationName = GetPlayerLocationName
-- TODO:
--[[
RP Finder utilizes ESO's Group Finder tool to create RP specific groups with tags that make them searchable with RP Finder, or even for anyone browsing the Custom Group Finder section.

Automatically generates group titles, descriptions, even links for people to visit if the RP is taking place within a home.  Go beyond visiting RP hubs determined by other people, create your own or visit others across Tamriel.

Dependencies:
LibSlashCommander

[B]Commands:[/B]
/rpfinder - show help (settings coming soon)
/rpfinder new|create - create and populate a new RP group
/rpfinder show - show all RP groups
/rpfinder zone - show all RP groups in current zone
/rpfinder home - show all RP groups in housing

Arguments:
/rpfinder new <type> can include:
[LIST]
[*]Adventure
[*]Casual
[*]Social
[*]Training
[*]Education
[*]Recruiting
[*]Exploration
[/LIST]
]]--

-- TODO
-- Timer to check for new RP groups created
-- Disregard pvp areas?
-- RP Theme, Guild, Uses Dice

-- Current Structure
-- Type:Theme:Guild:GuildOnly:UsesDice:LocationData

-- Snippets and shortcuts

local function sprintf(formatString, ...)
    return formatString:format(...)
end

local srep = string.rep

local function lpad(s, l, c)
    local res = srep(c or ' ', l - #s) .. s
    return res, res ~= s
end

local function rpad(s, l, c)
    local res = s .. srep(c or ' ', l - #s)
    return res, res ~= s
end

local function cpad(s, l, c)
    c = c or ' '
    local res1, stat1 = rpad(s, (l /2 ) + #s, c)
    local res2, stat2 = lpad(res1, l, c)
    return res2, stat1 or stat2
end

local RPTypes = {
    "",
    "Casual ",
    "Social ",
    "Adventure ",
    "Exploration ",
    "Training ",
    "Education ",
}

local function GetRPType(rpType)
    for i, val in ipairs(RPTypes) do
        if LocaleAwareToLower(rpType) .. " " == LocaleAwareToLower(val) then
            -- ROLE_PLAY_FINDER_MANAGER:Echo("%s = %s", rpType, val)
            return i
        else
            -- ROLE_PLAY_FINDER_MANAGER:Echo("%s is not %s", rpType, LocaleAwareToLower(val))
        end
    end
    ROLE_PLAY_FINDER_MANAGER:Echo("RP Type '%s' not found", rpType)
    return 1
end

local LocationType = {
    "Open World",
    "Player Housing",
}


local RPFinder = ZO_Object:Subclass()

function RPFinder:New(...)
    local obj = ZO_Object.New(self)
    obj:Initialize(...)
    return obj
end

function RPFinder:Initialize(...)
    self:BuildGroupFinder()

    self.isCreated = false

    self.RPDetails = {}

    self.RPDetails.Type = 1
    self.RPDetails.Guild = 0
    self.RPDetails.GuildOnly = 0
    self.RPDetails.ZoneIndex = 0
    self.RPDetails.UsesDice = 0
    self.RPDetails.LocationType = LOCATION_TYPE_WORLD
    self.RPDetails.X = 0 -- If player house, players name
    self.RPDetails.Y = 0 -- If playe rhouse, house ID
    self.RPDetails.Owner = "None"
end

function RPFinder:BuildDetails()
    self:FetchLocationData()
    local details = sprintf("%d:%d:%d:%d:%d:%d:%d:%d:%s:", self.RPDetails.Type,
            self.RPDetails.Guild,
            self.RPDetails.GuildOnly,
            self.RPDetails.UsesDice,
            self.RPDetails.LocationType,
            self.RPDetails.ZoneIndex,
            self.RPDetails.X, -- Will be house number if it's a home
            self.RPDetails.Y,
            self.RPDetails.Owner
    )
    self.RPDetails.DetailString = details
end

-- Determine if the player is in a home or open world, and fill out data accordingly
function RPFinder:FetchLocationData()
    local houseId = GetCurrentZoneHouseId()
    if (houseId and houseId > 0) then
        local owner = GetCurrentHouseOwner()
        self.RPDetails.LocationType = LOCATION_TYPE_HOUSING
        self.RPDetails.Owner = owner
        self.RPDetails.ZoneIndex = houseId
        return
    else
        self.RPDetails.LocationType = LOCATION_TYPE_WORLD
        self.RPDetails.X = 0
        self.RPDetails.Owner = ""
        self.RPDetails.ZoneIndex = GetUnitZoneIndex("player")
    end
end

function RPFinder:GetRPData(line)
    local data = {}

    for str in string.gmatch(line, "[^:]+") do
        table.insert(data, str)
    end

--    for i, info in ipairs(data) do
--        df("Data: %d %s", i, info)
--    end

    local dataRP = {}
    dataRP.Type = tonumber(data[1])
    dataRP.Guild = tonumber(data[2])
    dataRP.GuildOnly = tonumber(data[3])
    dataRP.UsesDice = tonumber(data[4])
    dataRP.LocationType = tonumber(data[5])
    dataRP.ZoneIndex = tonumber(data[6])
    dataRP.X = tonumber(data[7])
    dataRP.Y = tonumber(data[8])
    dataRP.Owner = data[9]

    return dataRP
end

function RPFinder:BuildGroupFinder(doCreate)
    GROUP_FINDER_SEARCH_MANAGER:RefreshSearchResults()
    self.GroupFinderResults = GROUP_FINDER_SEARCH_MANAGER:GetSearchResults()

    -- Get all the RP groups
    -- Clear data
    self.RPGroups = {}
    --df("Checking results...")

    -- PLayer has a custom group, let's play with it
    if GROUP_FINDER_KEYBOARD.createGroupListingContent.userTypeData:GetCategory() == 6 then
        self.isCreated = true
    end

    -- Add the player created one for testing purposes
    if self.isCreated then
        local playerData = GROUP_FINDER_KEYBOARD.createGroupListingContent.userTypeData
        if not self.GroupFinderResults then
            --df("No Group Finder Results")
            return
        end
        playerData.GetListingIndex = function()  return #self.GroupFinderResults + 1 end
        self.GroupFinderResults[#self.GroupFinderResults + 1] = playerData
    else
        dbPlayerData = GROUP_FINDER_KEYBOARD.createGroupListingContent.userTypeData
    end

    dbresults = self.GroupFinderResults

    --df("Proceeding to scan %d results...", #self.GroupFinderResults)

    local RPCount = 0

    for i, data in ipairs(self.GroupFinderResults) do
        -- Is it a custom category?
        if (data:GetCategory() == 6) then
            -- Does it contain the RP string
            local description = data:GetDescription()
            local tagStart, tagEnd = string.find(description, "#rp:")
            if (tagEnd) then
                local firstExtract = string.sub(description, tagEnd + 1)
                local tagStart2, tagEnd2= string.find(firstExtract, "#rp")
                local extract = string.sub(firstExtract, 1, tagStart2 - 1)
                --df("%d %d: %s/%s", tagStart, tagEnd, firstExtract, extract)
                local dataRP = self:GetRPData(extract)
                if (dataRP.LocationType == LOCATION_TYPE_WORLD) then
                    if (GetUnitZoneIndex("player") == dataRP.ZoneIndex) then
                        --df("Found a zone")
                        RPCount = RPCount + 1
                    else
                        --df("Not the zone")
                    end
                else
                    --df("Location Type is %d", dataRP.LocationType)
                end
                dataRP.groupFinderResult = data
                self.RPGroups[#self.RPGroups + 1] = ZO_ShallowTableCopy(dataRP)
                self.RPGroups[#self.RPGroups].groupFinderResult = data
            else
                --df("Tag not found")
                end
        else
            --df("Wrong category")
        end
    end
    if RPCount > 0 then
        --df("RPCount = %d", RPCount)
    end
end

function RPFinder:ApplyToGroup(index)
    return RequestApplyToGroupListing(index)
--    * RequestApplyToGroupListing(*luaindex* _listingIndex_, *string* _optionalMessage_, *integer:nilable* _inviteCode_)
--    ** _Returns:_ *[GroupFindGrouperActionResult|#GroupFinderActionResult]* _result_
end

function RPFinder:ShowGroupFinder(groupShow)

    self:BuildGroupFinder()

    self:ColorEcho("cornflowerblue", "RP Group Search Results:")
    if showSpoofData then
        -- Spoof for ESOUI
        local owner = ZO_LinkHandler_CreateLink("Captain Faeryl", nil, 'groupFind', 1)
        local title = "RP at Fall's Run"
        local desc = "Social tavern RP in the Run Inn"

        self:ColorEcho("lightgreen", "%s - %s: %s", owner, title, desc)

        local owner = ZO_LinkHandler_CreateLink("Tanglewen", nil, 'groupFind', 1)
        local title = "Adventure RP at Quire's Wind"
        local desc = "Roleplay the Exploration of Quire's Wind!"

        self:ColorEcho("lightgreen", "%s - %s: %s", owner, title, desc)

    end

    local isFound = false

    for k, data in pairs(self.RPGroups) do
        dbdata = data

       -- local owner = rpad("Character Name", 40)
        --local title = rpad("Title", 50)
        --self:ColorEcho("lightgreen", "%s%sDescription", owner, title)
        --df("%s%sDescription", owner, title)


        if groupShow == GROUP_SHOW_ALL or
                (groupShow == GROUP_SHOW_ZONE and data.ZoneIndex == GetUnitZoneIndex("player")) or
                (groupShow == GROUP_SHOW_HOUSING and data.locationType == LOCATION_TYPE_HOUSING)
            then
            local groupFinderResult = data.groupFinderResult
            -- df(groupFinderResult:GetOwnerCharacterName())
            local ownerName = groupFinderResult:GetOwnerCharacterName()
            dbGF = groupFinderResult

            local i = groupFinderResult.GetListingIndex and groupFinderResult:GetListingIndex() or 0
            i = 1
            local index = sprintf("%d", i or 0)
            local owner = ZO_LinkHandler_CreateLink(ownerName, nil, 'groupFind', index)


            local title = groupFinderResult:GetTitle()
            local desc = groupFinderResult:GetDescription()

            local tagStart, tagEnd = string.find(desc, "#rp:")
            -- Go back 2 to remove linefeed
            local extractedDesc = string.sub(desc, 0, tagStart -2)

            self:ColorEcho("lightgreen", "%s - %s: %s", owner, title, extractedDesc)

            if data.UsesDice == 1 then
                self:Echo("     This RP Group uses dice to determine outcomes.")
            end
            if data.Guild > 0 then
                local guildName = GetGuildName(data.Guild)
                if guildName then
                    --|H1:guild:857107|hReaper's Brigade|h
                    local link = sprintf("     |H1:guild:%d|h%s|h", data.Guild, guildName)
                    self:Echo(link)
                end
            end

            -- df("%s%s%s", owner, title, desc)
            -- self:ColorEcho("lightgreen", "%d %d", data.LocationType, data.Guild)
            if data.LocationType == LOCATION_TYPE_HOUSING then
                local link = GetHousingLink(data.ZoneIndex, data.Owner)
                -- The description has a link, don't show it again
                local linkFound = string.find(extractedDesc, link)
                if not linkFound then
                    self:ColorEcho("lightblue", "     %s", link)
                else
                    -- self:ColorEcho("lightblue", "     Redundant Link", linkFound)
                end
            end
            isFound = true

        end
    end
    if not isFound then
        self:ColorEcho("lightgreen", "No RP Groups found!  You can create one with /rpfinder new")
    end
end


function RPFinder:CreateRPGroup()
    -- Test created
    if GROUP_FINDER_KEYBOARD then
        GROUP_FINDER_KEYBOARD.createGroupListingContent:UpdateUserType()
        local data = GROUP_FINDER_KEYBOARD.createGroupListingContent.userTypeData
--        df("GF found")

        --if data:GetCategory() ~= 6 then
        --end
        --df("%s %d", data:GetTitle(), data:GetCategory())
        self:BuildGroupFinder()
        -- TEsting: Create AFTER first build
        self.isCreated = true
        self:CreateRPListing()

        --        data:SetDescription("This is a test of an RP finding AddOn\nIt seems to be working so far!")
        --        data:SetDescription("This is a test of an RP finding AddOn\nIt seems to be working so far!")
    else
        --df("GF Not Found")
    end
end

function RPFinder:CheckForNewGroups()

end

function RPFinder:GetGuildId(guildIndex)
    if not guildIndex then return 0 end
    guildIndex = tonumber(guildIndex)
    if guildIndex > 5 or guildIndex > GetNumGuilds() then
        return 0
    end
    return GetGuildId(guildIndex)
end

function RPFinder:SetUsesDice(usesDice)
    self.RPDetails.UsesDice = tonumber(usesDice)
    self:BuildDetails()
end

function RPFinder:GetUsesDice()
    return self.RPDetails.UsesDice
end

function RPFinder:SetCreated(isCreated)
    self.isCreated = isCreated
end

function RPFinder:SetRPType(rpType)
    self.RPDetails.Type = rpType
end

function RPFinder:GetCreated()
    return self.isCreated
end

function RPFinder:RemoveRPListing()
    if not self.isCreated then
        self:ColorEcho("lightgreen", "You have no RP Group Listed")
        return
    end
    RequestRemoveGroupListing()
    self:ColorEcho("goldenrod", "RP Group Listing Removed")
end

local numberOfListings = 0

function RPFinder:CreateRPListing()
    if not GROUP_FINDER_KEYBOARD then
        return
    end

    numberOfListings = numberOfListings + 1

    local data = GROUP_FINDER_KEYBOARD.createGroupListingContent.userTypeData
    data:SetCategory(6)
    self:BuildDetails()
    local description

    local locationName = GetPlayerLocationName()

    local rpType = self.RPDetails.Type or 1
    -- ROLE_PLAY_FINDER_MANAGER:Echo("TP Type: %d", rpType)
    local title = sprintf("%sRP at %s", RPTypes[rpType], locationName)
    data:SetTitle(title)

    -- TODO: Add RP type
    if self.RPDetails.LocationType == LOCATION_TYPE_HOUSING then
        local link = GetHousingLink(self.RPDetails.ZoneIndex, self.RPDetails.Owner)
        description = sprintf("RP at %s\n#rp:%s#rp!", link, self.RPDetails.DetailString)
    else
        description = sprintf("RP at %s\n#rp:%s#rp!", locationName, self.RPDetails.DetailString)
    end

    data:SetDescription(description)

    if data:GetUserType() == GROUP_FINDER_GROUP_LISTING_USER_TYPE_CREATED_GROUP_LISTING then
        --df("Editing RP Listing")
        RequestEditGroupListing()
    else
        --df("Creating RP Listing")
        RequestCreateGroupListing()
    end
end

-- Iterate through all RP groups, count local ones
function RPFinder:GetLocalRPCount()
    local RPCount = 0
    for k, value in pairs(self.RPGroups) do
        if (value.ZoneIndex == GetUnitZoneIndex("player")) then
            --df("Same Zone Index")
            RPCount = RPCount + 1
        end
    end
    -- self:ColorEcho("lightgreen", "RPCount: %d", RPCount)
    if RPCount > 0 then
        self:ColorEcho("lightgreen", "There is RP in this zone!  Type \"/rpfinder zone\" to see them.  Groups: %d", RPCount)
    end
end

ROLE_PLAY_FINDER_MANAGER = RPFinder:New()
ROLE_PLAY_FINDER_MANAGER.Utils = {}
ROLE_PLAY_FINDER_MANAGER.Resources = {}

local function onAddonLoaded(event, name)
    -- return early, return often
    if (name ~= ADDON_NAME) then return end
    -- RPFinder.Data = SavedVars:New(name)

    -- LibKaTTek.Data.Saved.Windows = LibKaTTek.Data.Saved.Windows or {}

    -- Create Icon Cache for default style
    -- LibKaTTek.Resources:CreateIconCache()

    df("RPFinder loaded")
    EVENT_MANAGER:UnregisterForEvent(name, EVENT_ADD_ON_LOADED)
end

local function onPlayerActivated(name)
    --df("Player Activated!")
    if ROLE_PLAY_FINDER_MANAGER:GetCreated() then
        ROLE_PLAY_FINDER_MANAGER:CreateRPListing()
    end

    SetGroupFinderFilterCategory(6)
    GROUP_FINDER_SEARCH_MANAGER:ExecuteSearch()

    ROLE_PLAY_FINDER_MANAGER:BuildGroupFinder()
    ROLE_PLAY_FINDER_MANAGER:GetLocalRPCount()
    -- TODO: Only do this once
    if not ROLE_PLAY_FINDER_MANAGER.SlashCommands then
        ROLE_PLAY_FINDER_MANAGER.SlashCommands = LibSlashCommander

        local rpfCommand = ROLE_PLAY_FINDER_MANAGER.SlashCommands:Register(
                { "/rpfinder", "/finder" },
                function(input)
                    -- break up input
                    local splitInput = { zo_strsplit(" ", input) }
                    --ROLE_PLAY_FINDER_MANAGER:Echo("%s", splitInput[1] or input)
                    input = splitInput[1] or input
                    if (input == "create" or input == "new") then
                        if splitInput[2] then
                            --ROLE_PLAY_FINDER_MANAGER:Echo("Checking for RP type %s", splitInput[2])
                            local RPType = GetRPType(splitInput[2])
                            ROLE_PLAY_FINDER_MANAGER:SetRPType(RPType)
                        end

                        ROLE_PLAY_FINDER_MANAGER:ColorEcho("lightblue", "Creating new RP group...")
                        ROLE_PLAY_FINDER_MANAGER:CreateRPGroup()
                    elseif (input == "show") then
                        ROLE_PLAY_FINDER_MANAGER:ShowGroupFinder(GROUP_SHOW_ALL)
                    elseif (input == "zone") then
                        ROLE_PLAY_FINDER_MANAGER:ShowGroupFinder(GROUP_SHOW_ZONE)
                    elseif (input == "house") or input == "home" then
                        ROLE_PLAY_FINDER_MANAGER:ShowGroupFinder(GROUP_SHOW_HOUSING)
                    elseif (input == "guild") then
                        if not(splitInput[2]) then
                            local guildId = ROLE_PLAY_FINDER_MANAGER.RPDetails.Guild
                            local guildName = GetGuildName(guildId)
                            ROLE_PLAY_FINDER_MANAGER:ColorEcho("lightblue", "Your RP Group is linked to guild %s", guildName)
                        else
                            local guildId = ROLE_PLAY_FINDER_MANAGER:GetGuildId(splitInput[2])
                            ROLE_PLAY_FINDER_MANAGER.RPDetails.Guild = guildId
                            local guildName = GetGuildName(guildId)
                            ROLE_PLAY_FINDER_MANAGER:ColorEcho("lightblue", "Your RP Group is linked to guild %s", guildName)
                            ROLE_PLAY_FINDER_MANAGER:BuildDetails()
                            if ROLE_PLAY_FINDER_MANAGER:GetCreated() then
                                ROLE_PLAY_FINDER_MANAGER:CreateRPListing()
                            end
                        end
                    elseif (input == "usedice") then
                        local useDice = ROLE_PLAY_FINDER_MANAGER:GetUsesDice()
                        -- TODO: Different types of dice rules?
                        if useDice == 0 then
                            useDice = 1
                        else
                            useDice = 0
                        end
                        ROLE_PLAY_FINDER_MANAGER:SetUsesDice(useDice)
                        if (useDice == 1) then
                            ROLE_PLAY_FINDER_MANAGER:ColorEcho("lighblue", "Your RP Group uses dice.")
                        else
                            ROLE_PLAY_FINDER_MANAGER:ColorEcho("lighblue", "Your RP Group does not use dice.")
                        end
                        if ROLE_PLAY_FINDER_MANAGER:GetCreated() then
                            ROLE_PLAY_FINDER_MANAGER:CreateRPListing()
                        end

                    elseif (input == "end" or input == "remove") then
                        ROLE_PLAY_FINDER_MANAGER:RemoveRPListing()
                    end
                end
        )

        -- SLASH_COMMANDS["/rpfinder"] = function() ROLE_PLAY_FINDER_MANAGER:ShowGroupFinder() end
    end
end

local function onGroupMemberLeft(memberCharacterName, reason, isLocalPlayer, isLeader, memberDisplayName, vote)
    if not isLocalPlayer then
        return
    end
    ROLE_PLAY_FINDER_MANAGER:SetCreated(false)
end

local function onGroupListingRemoved(reason)
    --df("Group Listing Removed")
    ROLE_PLAY_FINDER_MANAGER:SetCreated(false)
end

local function OnLinkClicked(linkData, button, linkText, color, linkType, ...)
    local command = {...}

    -- TODO: Right click menu?

    if linkType ~= "groupFind" or button ~= 1 then
        return false
    end

    if not command[1] then
        return
    end

    local index = tonumber(command[1])
    ROLE_PLAY_FINDER_MANAGER:Echo("Found Index %d", index)
    if (index and index > -1) then
        ROLE_PLAY_FINDER_MANAGER:ApplyToGroup(index)
    end
    return true
end

local function OnSearchResultsReady()
    -- Only build if results are for custom group
    if GetGroupFinderFilterCategory() == 6 then
        --ROLE_PLAY_FINDER_MANAGER:ColorEcho("red", "Search Results Ready, building...")
        ROLE_PLAY_FINDER_MANAGER:BuildGroupFinder()
    end
end

EVENT_MANAGER:RegisterForEvent(ADDON_NAME, EVENT_ADD_ON_LOADED, onAddonLoaded)
EVENT_MANAGER:RegisterForEvent("onRPFTest", EVENT_PLAYER_ACTIVATED, onPlayerActivated)
EVENT_MANAGER:RegisterForEvent("GroupLeft", EVENT_GROUP_MEMBER_LEFT, onGroupMemberLeft)
EVENT_MANAGER:RegisterForEvent("GroupRemoved", EVENT_GROUP_FINDER_REMOVE_GROUP_LISTING_RESULT, onGroupListingRemoved)
LINK_HANDLER:RegisterCallback(LINK_HANDLER.LINK_MOUSE_UP_EVENT, OnLinkClicked)
GROUP_FINDER_SEARCH_MANAGER:RegisterCallback("OnGroupFinderSearchResultsReady", OnSearchResultsReady)
